using System;
using System.Collections.Generic;
using System.Linq;
using Bloomlings.Core.Variants;

namespace Bloomlings.Client.UI.Design
{
    /// <summary>The asset categories of FR-029.</summary>
    public enum AssetCategory
    {
        Brand,
        Background,
        Character,
        VariantSymbol,
        BoardTile,
        Special,
        PodSlot,
        Booster,
        UiKit,

        /// <summary>The reference look's materials (spec 005 FR-006): wood, stone, parchment.</summary>
        Material,
        Currency,
        CollectionFrame,
        Cosmetic,
        Effect,
        Typography,
        Audio,
    }

    /// <summary>The size class of an asset (data-model "AssetSlot").</summary>
    public enum SizeClass
    {
        /// <summary>Up to 96 px.</summary>
        Icon,

        /// <summary>Up to 192 px.</summary>
        Small,

        /// <summary>Up to 512 px.</summary>
        Medium,

        /// <summary>Up to 1024 px.</summary>
        Large,

        /// <summary>Full screen.</summary>
        Screen,

        /// <summary>A sound or music file.</summary>
        Audio,
    }

    /// <summary>Whether an asset is needed for launch.</summary>
    public enum AssetPriority
    {
        Launch,
        Later,
    }

    /// <summary>How the game stands in for the asset today.</summary>
    public enum PlaceholderKind
    {
        /// <summary>A <see cref="ShapeLibrary"/> shape with the slot's id.</summary>
        Shape,

        /// <summary>Drawn in code from tokens (backdrops, tile shading, cards, effects).</summary>
        Procedural,

        /// <summary>Text in the system font (the wordmark).</summary>
        Text,

        /// <summary>A synthesized sound (<c>ToneSynth</c>).</summary>
        Synth,

        /// <summary>The platform's bold or regular sans-serif.</summary>
        SystemFont,

        /// <summary>A font file bundled with the game (spec 003: Nunito, SIL OFL 1.1).</summary>
        BundledFont,

        /// <summary>Not drawn inside the game (the app icon): the platform default for now.</summary>
        External,

        /// <summary>A picture generated by <c>tools/artgen</c> and committed as the project's own art (spec 004).</summary>
        Generated,
    }

    /// <summary>
    /// One needed art or audio asset and the placeholder standing in for it (contracts/asset-slots.md). The inventory
    /// document is generated from these entries.
    /// </summary>
    public sealed record AssetSlot(
        string Id,
        AssetCategory Category,
        string Title,
        IReadOnlyList<int> Frames,
        IReadOnlyList<string> UsedIn,
        IReadOnlyList<string> States,
        SizeClass Size,
        bool Readability,
        AssetPriority Priority,
        PlaceholderKind Kind,
        string Placeholder);

    /// <summary>
    /// The registry of every asset slot (research R10, FR-029, FR-030). Every placeholder the Unity client or the full
    /// playtest draws or plays resolves to a slot here, and every slot is used somewhere (SC-003, both ways): the
    /// client tests and the preview tool check this. <c>dotnet run --project playtest/preview -- --inventory</c> writes
    /// <c>specs/002-ux-design-board/asset-inventory.md</c> from it. Engine-free.
    /// </summary>
    public static class AssetSlots
    {
        // Declared before All: static initializers run in order, and Build() reads these.
        private static readonly int[] Gameplay = { 7, 8, 9 };

        /// <summary>The sound cues (<c>SoundCue</c>, lowercase) and where they play.</summary>
        public static IReadOnlyList<(string Cue, string Title, string Use)> Cues { get; } = new[]
        {
            ("click", "button click", "Every button"),
            ("tap", "pod committed", "Tray"),
            ("refused", "refused tap", "Tray"),
            ("clear", "tile restored", "Board"),
            ("poddone", "pod finished", "Slots"),
            ("key", "key collected", "Board"),
            ("special", "special triggered", "Board"),
            ("booster", "booster used", "Booster bar"),
            ("jam", "jam", "Jam sheet"),
            ("win", "win", "Win"),
        };

        /// <summary>The id prefixes of each category (contracts/asset-slots.md, "Id scheme").</summary>
        public static IReadOnlyDictionary<string, AssetCategory> Prefixes { get; } = new Dictionary<string, AssetCategory>(StringComparer.Ordinal)
        {
            ["brand."] = AssetCategory.Brand,
            ["bg."] = AssetCategory.Background,
            ["char."] = AssetCategory.Character,
            ["symbol."] = AssetCategory.VariantSymbol,
            ["tile."] = AssetCategory.BoardTile,
            ["board."] = AssetCategory.BoardTile,
            ["special."] = AssetCategory.Special,
            ["pod."] = AssetCategory.PodSlot,
            ["slot."] = AssetCategory.PodSlot,
            ["booster."] = AssetCategory.Booster,
            ["ui."] = AssetCategory.UiKit,
            ["icon."] = AssetCategory.UiKit,
            ["mat."] = AssetCategory.Material,
            ["currency."] = AssetCategory.Currency,
            ["collection."] = AssetCategory.CollectionFrame,
            ["cosmetic."] = AssetCategory.Cosmetic,
            ["fx."] = AssetCategory.Effect,
            ["font."] = AssetCategory.Typography,
            ["audio."] = AssetCategory.Audio,
        };

        public static IReadOnlyList<AssetSlot> All { get; } = Build();

        private static readonly Dictionary<string, AssetSlot> ById = All.ToDictionary(s => s.Id, StringComparer.Ordinal);

        public static bool Has(string id) => ById.ContainsKey(id);

        public static AssetSlot? Find(string id) => ById.TryGetValue(id, out AssetSlot? slot) ? slot : null;

        /// <summary>The category an id's prefix belongs to, or null for an unknown prefix.</summary>
        public static AssetCategory? CategoryOf(string id)
        {
            foreach (KeyValuePair<string, AssetCategory> prefix in Prefixes)
            {
                if (id.StartsWith(prefix.Key, StringComparison.Ordinal))
                {
                    return prefix.Value;
                }
            }

            return null;
        }

        private static List<AssetSlot> Build()
        {
            var list = new List<AssetSlot>();

            void Add(string id, string title, int[] frames, string usedIn, string states, SizeClass size, bool readability, AssetPriority priority, PlaceholderKind kind, string placeholder)
            {
                AssetCategory category = CategoryOf(id) ?? throw new InvalidOperationException("Unknown asset slot prefix: " + id);
                list.Add(new AssetSlot(id, category, title, frames, Split(usedIn), Split(states), size, readability, priority, kind, placeholder));
            }

            void Shape(string id, string title, int[] frames, string usedIn, string states, SizeClass size = SizeClass.Icon, bool readability = false, AssetPriority priority = AssetPriority.Launch) =>
                Add(id, title, frames, usedIn, states, size, readability, priority, PlaceholderKind.Shape, "shape `" + id + "`");

            const AssetPriority Launch = AssetPriority.Launch;
            const AssetPriority Later = AssetPriority.Later;

            // ---- Brand ----
            Add("brand.wordmark", "Bloomlings wordmark (logo): the owner's picture `Brand/logo.png` (spec 005 pictures.md C1)", new[] { 1, 2, 3 }, "Splash; Home", "full; compact", SizeClass.Large, false, Launch, PlaceholderKind.Text, "the wooden letters `ui.logo.wood` until the picture exists");
            Add("brand.tagline", "Tagline \"Small friends. Big gardens.\" (the owner's optional picture `Brand/tagline.png`, spec 005 pictures.md C2)", Array.Empty<int>(), "Splash; Home", "full", SizeClass.Medium, false, Later, PlaceholderKind.External, "none yet: neither build shows a tagline; the slot keeps the picture's place for later");
            Add("brand.splash_art", "Splash: the lotus loader (spec 005 FR-039): the logo and the lotus on the parchment with the ring of petals filling while the game loads, then the lotus iris opening on the first screen", new[] { 1 }, "Splash", "loading (the ring filling); opening", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "the wordmark (`brand.wordmark`), the lotus (`currency.petal`) and twelve `fx.petals` round it lighting up in `lotus.fill`, \"Loading...\" under them, on the iris' cover (`ui.lotus_iris`)");
            Add("brand.app_icon", "App icon", Array.Empty<int>(), "Launcher; store listing", "Android adaptive (foreground, background); iOS set", SizeClass.Medium, false, Launch, PlaceholderKind.External, "platform default icon");

            // ---- Backgrounds ----
            Add("bg.theme.daylight_garden", "Gameplay backdrop: Daylight Garden (levels 1–99 and every fourth band)", Gameplay, "Gameplay", "tall; short", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "procedural lush garden (spec 005 §4.2, FR-020: grass patches, fine blades and lighter paths; a deep `foliage.*` hedge, bushes and big leaves along the edges; many pink, white, orange and yellow flowers, big ones at the edges; a soft vignette) in fresh green until `Backgrounds/gameplay-daylight.png` exists (spec 005 pictures.md B2)");
            Add("bg.theme.pond", "Gameplay backdrop: Pond (from L100)", Gameplay, "Gameplay", "tall; short", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "procedural lawn tilted toward teal by the pond theme until `Backgrounds/gameplay-pond.png` exists (pictures.md B3)");
            Add("bg.theme.orchard", "Gameplay backdrop: Orchard (from L150)", Gameplay, "Gameplay", "tall; short", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "procedural lawn tilted warm by the orchard theme until `Backgrounds/gameplay-orchard.png` exists (pictures.md B4)");
            Add("bg.theme.moonlit_garden", "Gameplay backdrop: Moonlit Garden (from L200)", Gameplay, "Gameplay", "tall; short", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "procedural lawn, dusky and blue-green for the moonlit theme, until `Backgrounds/gameplay-moonlit.png` exists (pictures.md B5)");
            Add("bg.home", "Home scene: the garden behind the layered Home (sky, arches, flowers and paving, without the fountain: the owner's layer pack, spec 005 FR-028)", new[] { 2, 3 }, "Home", "early; progressed", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "procedural backdrop with arches until `Backgrounds/home.jpg` exists (pictures.md B1)");

            // Spec 005 FR-028: the owner's layered Home (HomeLayers, prepared by tools/heroanim/layers.mjs), drawn over
            // `bg.home` in its cover box, back to front, with the animated heroes between the layers.
            Add("bg.home.fountain_back", "Home layer: the fountain's basin (its pool, pedestal, waterfalls and the bushes behind it; Drop and Bloom stand in front of it; since 2026-10-08 the owner's basin without a lotus)", new[] { 2, 3 }, "Home", "portrait", SizeClass.Screen, false, Launch, PlaceholderKind.Generated, "the owner's picture `Backgrounds/home-fountain-back.png` (fitted by hand on 2026-10-08, tools/heroanim/layers.json); without it, or without the lotus or the front, Home shows the garden alone with no heroes");
            Add("bg.home.lotus", "Home layer: the lotus on the basin's pedestal, drawn over Bloom, who stands behind it (since 2026-10-08 the owner's lotus at 0.72)", new[] { 2, 3 }, "Home", "portrait", SizeClass.Medium, false, Launch, PlaceholderKind.Generated, "the owner's picture `Backgrounds/home-lotus.png` (fitted by hand on 2026-10-08, tools/heroanim/layers.json); without it Home shows the garden alone with no heroes");
            Add("bg.home.fountain_front", "Home layer: the fountain's front bushes in the corners, before the heroes (since 2026-10-08 the owner's two bushes at 0.82)", new[] { 2, 3 }, "Home", "portrait", SizeClass.Screen, false, Launch, PlaceholderKind.Generated, "the owner's picture `Backgrounds/home-fountain-front.png` (fitted by hand on 2026-10-08, tools/heroanim/layers.json); without it Home shows the garden alone with no heroes");
            Add("bg.home.shadow", "Home layer: the soft shadow under each hero's feet (one picture, as wide as the hero's seam pose)", new[] { 2, 3 }, "Home", "each hero", SizeClass.Medium, false, Launch, PlaceholderKind.Generated, "the owner's picture `Backgrounds/home-shadow.png` at 85% opacity (tools/heroanim/layers.mjs); without it the heroes stand without shadows");
            Add("bg.splash", "Splash backdrop: the lotus loader's parchment (spec 005 FR-039)", new[] { 1 }, "Splash", "portrait", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "`parchment.bottom` with a soft `parchment.top` light behind the lotus (the iris' cover, `ui.lotus_iris`); the owner's `Backgrounds/splash.png` (pictures.md B6) is not shown while the lotus loader is the splash");
            Add("bg.wardrobe", "The pages' backdrop: the garden arches behind the Wardrobe's hero on its pedestal and behind the Store, Leaderboard and Collection pages (both builds)", new[] { 5, 6, 17 }, "Wardrobe; Store; Leaderboard; Collection", "portrait", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "the warm Home garden backdrop (`HomeStage.Garden`) until `Backgrounds/wardrobe.png` exists (pictures.md B7)");
            Add("bg.win", "Win backdrop: the garden behind the full-screen celebration, calm in the middle with soft light from it (spec 005 FR-023)", new[] { 15, 16 }, "Win; milestone", "portrait", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "the level's lawn (`BackdropScene.Win`) rendered at an eighth (blurred), lightened toward cream with a warm `ray.light` glow in the middle, until `Backgrounds/win.png` exists (pictures.md B8)");

            // ---- Characters ----
            Shape("char.sprig", "Sprig family body (the fallback figure when a picture is missing)", new[] { 2, 3, 7, 8, 9, 12, 13 }, "Pods; slots; walkers; Home; demos", "idle; walk; work; finish; stuck; celebrate", SizeClass.Medium, readability: true);
            Shape("char.bloom", "Bloom family body (the fallback figure when a picture is missing)", new[] { 2, 3, 7, 8, 9, 12, 13 }, "Pods; slots; walkers; Home; demos", "idle; walk; work; finish; stuck; celebrate", SizeClass.Medium, readability: true);
            Shape("char.drop", "Drop family body (the fallback figure when a picture is missing)", new[] { 2, 3, 7, 8, 9, 12, 13 }, "Pods; slots; walkers; Home; demos", "idle; walk; work; finish; stuck; celebrate", SizeClass.Medium, readability: true);
            Shape("char.twig", "Twig family body (the fallback figure when a picture is missing)", new[] { 2, 3, 7, 8, 9, 12, 13 }, "Pods; slots; walkers; Home; demos", "idle; walk; work; finish; stuck; celebrate", SizeClass.Medium, readability: true);
            Add("char.hero.home", "Home hero: a large Bloomling in the player's outfit", new[] { 3 }, "Home", "idle; reaction; each family; outfit layers", SizeClass.Large, false, Launch, PlaceholderKind.Generated, "over the owner's layered Home the family's animated hero (`char.hero3d.motion.{family}`) with worn cosmetics; on the drawn stand-in its 3D solo hero `3d/{family}`");

            // Spec 004: each variant is a 2D character whose whole shape is its symbol, and each family a 3D hero for the
            // meta screens. The pictures are generated by tools/artgen (contracts/art-files.md).
            foreach (VariantInfo variant in VariantCatalog.Default.All)
            {
                bool atLaunch = variant.Status == VariantStatus.Launch;
                Add(CharacterArt.Slot2D(variant.IconId), "Variant character: " + variant.Id.Key + " (its shape is the symbol)", new[] { 7, 8, 9, 12, 13 }, "Pods; slots; walkers; board tiles", "happy; asleep (queued); worried (stuck); blank (worn expression)", SizeClass.Small, true, atLaunch ? Launch : Later, PlaceholderKind.Generated, "`2d/" + variant.IconId + "-{mood}.png`");
            }

            foreach (Family family in CharacterArt.Families)
            {
                Add(CharacterArt.HeroSlot(family), "3D hero: " + family, new[] { 3, 5 }, "Home; Wardrobe; profile; leaderboard", "face; blank (worn expression)", SizeClass.Medium, false, Launch, PlaceholderKind.Generated, "`" + CharacterArt.Hero(family) + ".png`");
            }

            Add(CharacterArt.GroupSlot, "3D heroes: the four families side by side (the hosts stand them on a stone pedestal)", new[] { 15, 16 }, "Win; milestone", "warm garden light", SizeClass.Large, false, Launch, PlaceholderKind.Generated, "`" + CharacterArt.Group + ".png`");
            foreach (Family family in CharacterArt.Families)
            {
                Add(CharacterArt.CheerSlot(family), "3D hero celebrating: " + family + " (the owner's picture, spec 005 pictures.md A7)", new[] { 15, 16 }, "Win; milestone (the level's main family)", "arms up, eyes closed with joy", SizeClass.Large, false, Later, PlaceholderKind.Generated, "none while the animated hero's frames exist (`" + HeroMotion.Slot(family) + "` celebrates instead); without them `" + CharacterArt.Cheer(family) + ".png`, and the group picture `" + CharacterArt.Group + ".png` without both");
            }

            // Spec 005 FR-028: the owner's animated FBX heroes, pre-rendered offline by tools/heroanim into flat frames
            // (constitution VII: no 3D model, scene or camera in the game; flat pictures on meta screens only).
            foreach (Family family in CharacterArt.Families)
            {
                string name = CharacterArt.FamilyName(family);
                Add(HeroMotion.Slot(family), "3D hero in motion: " + family + " (the owner's animated hero as pre-rendered flat frames, " + HeroMotion.Fps + "/s; spec 005 FR-028)", new[] { 2, 3, 15, 16 }, "Home (around the lotus fountain, a tap makes it react); win and milestone (the level's main family)", "idle loop (4 s, breathing and sway); reaction (2 s, from and back to the idle's first pose, cross-fading when tapped mid-loop); outfit layers", SizeClass.Large, false, Launch, PlaceholderKind.Generated, "`" + HeroMotion.Folder + "/" + name + "-idle-NN.png` and `" + name + "-react-NN.png` (tools/heroanim), decoded when first drawn; while they are missing, the still hero `" + CharacterArt.Hero(family) + ".png` (Home) or `" + CharacterArt.Cheer(family) + ".png` (win)");
            }

            // ---- Variant symbols ----
            string[] launch = { "leaf", "moss", "flower", "bud", "drop", "dew", "log", "acorn" };
            string[] names = { "Leaf", "Moss", "Flower", "Violet Bud", "Water", "Dew", "Wood", "Acorn" };
            for (int i = 0; i < launch.Length; i++)
            {
                Shape("symbol." + launch[i], "Variant symbol: " + names[i], new[] { 7, 8, 9, 12, 13 }, "Tiles; pods; slots; walkers; demos; jam sheet", "tile; pod; slot; small", SizeClass.Icon, readability: true);
            }

            string[] expansion = { "vine", "berry", "mist", "bark" };
            string[] expansionNames = { "Vine", "Berry", "Mist", "Bark" };
            for (int i = 0; i < expansion.Length; i++)
            {
                Shape("symbol." + expansion[i], "Variant symbol: " + expansionNames[i] + " (expansion)", new[] { 7, 8, 9 }, "Tiles; pods; slots; walkers", "tile; pod; slot; small", SizeClass.Icon, readability: true, priority: Later);
            }

            // ---- Board tiles and overlays ----
            Add("tile.base", "Board tile (a target cell's top layer)", Gameplay, "Board", "normal; mystery; clearing (shrinks and fades)", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "the candy tile `tile.candy` (board style) nearly filling its cell, parted from its neighbors by the dark board gap");
            Add("tile.layer_peek", "Layered tile: the next layer peeking", Gameplay, "Board", "2 layers; 3 layers", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "a small candy tile of the next layer in a cream ring with a dark rim, in the tile's top-right corner");
            Shape("tile.mystery", "Mystery tile and mystery pod mark (?)", new[] { 9, 12 }, "Board; pods; slots", "hidden; revealing", SizeClass.Small, readability: true);
            Shape("tile.stone", "Stone blocker: the rock glyph carved into a raised sandy stone block (`mat.stone`)", new[] { 7, 9 }, "Board", "whole; cracking", SizeClass.Small, readability: true);
            Shape("tile.key", "Key (gold, on a cream disc in the tile's top-left corner)", new[] { 9 }, "Board; flights to locks", "on tile; flying", SizeClass.Icon, readability: true);
            Add("tile.ground", "Open ground (a restored cell of a picture role)", Gameplay, "Board", "restored", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "pale flat cell of the finished picture (its variant color lightened), small radius, faint inner shadow");
            Add("tile.grass", "Grass cell: a board cell of the picture's background (no role), so the board reads as garden (spec 005 FR-020)", new[] { 7, 8, 9, 15 }, "Board; finished picture (win, Collection)", "open; background", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "UiRaster.Grass picture: a muted lawn square with a soft mottle, short blades, a faint top shadow and a deeper rim (four variants)");
            // Spec 005 §3.1, §3.6: the candy tiles (UiRaster.Tile) and the stone border around the board.
            Add("tile.candy", "Candy tile, board style: a soft cube in the variant color (spec 005 FR-044: a rounded square top whose edges round down, lit from the upper left, over a deeper front face) with its symbol as a bold gem on the top's middle (spec 005 FR-026: a thick dark outline, a fill in a shade of the tile, a white highlight); the owner's field icon (`tile.gem.*`) replaces the drawn gem", Gameplay, "Board; demos", "normal; pressed; dimmed; grey; mystery", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "UiRaster.Tile picture (board style, the soft cube of UiRaster.Cube, `ShapeLibrary.GemSymbol`); with the owner's icon the face alone (`UiRaster.TileFace`) under the picture");
            Add("tile.candy.sticker", "Candy tile, sticker style: a detailed symbol with a dark outline in its own tone; the owner's detailed icon (`tile.icon.*`) replaces the drawn symbol", new[] { 7, 10, 12, 13 }, "Pods; slots; jam sheet; Collection", "normal; dimmed (queued); grey (stuck); mystery", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "UiRaster.Tile picture (sticker style); with the owner's icon the face alone (`UiRaster.TileFace`) under the picture");

            // Spec 005 pictures.md G9–G24: the owner's variant icons over the candy tile's face (OwnerPictures.TileIcon).
            for (int i = 0; i < launch.Length; i++)
            {
                Add(OwnerPictures.IconSlot(launch[i]), "Variant icon, detailed: " + names[i] + " (the owner's picture `Icons/" + OwnerPictures.VariantIcon(launch[i]) + ".png`, spec 005 pictures.md G" + (9 + i) + ")", new[] { 7, 10, 12, 13 }, "Pods; slots; jam sheet; flights; demos; kit sheet", "normal; dimmed (queued, faded); grey (stuck, a grey copy); pressed", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "the drawn sticker symbol `symbol." + launch[i] + "` (UiRaster.Tile, sticker style) until the picture exists; it covers about 70% of the tile");
            }

            for (int i = 0; i < launch.Length; i++)
            {
                Add(OwnerPictures.GemSlot(launch[i]), "Variant icon, simplified for the board: " + names[i] + " (the owner's picture `Icons/" + OwnerPictures.FieldIcon(launch[i]) + ".png`, spec 005 pictures.md G" + (17 + i) + ")", new[] { 7, 8, 9, 15 }, "Board tiles; layer peeks; specials; finished picture (win, Collection)", "normal; flat (finished picture)", SizeClass.Icon, true, Launch, PlaceholderKind.Procedural, "the drawn gem (`ShapeLibrary.GemSymbol`, UiRaster.Tile, board style) until the picture exists; it covers about 62% of the tile");
            }

            Add("board.entry.arch", "Garden Entry: a small stone arch set in the border beside each entry cell (spec 005 FR-034; the owner's choice \"B\", 2026-10-05)", Gameplay, "Board (every entry, turned to its side)", "bottom; top; left; right", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "UiRaster.EntryArch: two stone pillars and an arch of keystones round a dark opening with two peeping eyes, ivy, a pink flower on the keystone and a soft warm light; it reaches 0.36 cell over the entry cell");
            Add("board.border.stone", "Stone border around the board", Gameplay, "Board; win picture", "normal; thin (win)", SizeClass.Large, true, Launch, PlaceholderKind.Procedural, "UiRaster.Stone blocks (warm sandy stone) with dark joints, and dark lines between the tiles");
            Add("tile.picture", "Finished picture reveal", new[] { 6, 15 }, "Win; Collection", "reveal; framed", SizeClass.Large, true, Launch, PlaceholderKind.Procedural, "the level's cells as the board's soft cubes (`tile.candy`, with the owner's field icons `tile.gem.*`; spec 005 FR-046: \"as in the gameplay, volumetric\") of each role's variant in a thin stone border (spec 005 D14)");

            // ---- Specials ----
            Shape("special.gate", "Garden Gate (hedge seal)", new[] { 9 }, "Board", "closed; opening", SizeClass.Small, readability: true);
            Shape("special.fountain", "Fountain (also the bottom menu's Home stand-in)", new[] { 9 }, "Board; bottom menu (while `Icons/nav-home.png` is missing)", "dry; flowing", SizeClass.Small, readability: true);
            Shape("special.chest", "Sealed Chest", new[] { 9 }, "Board", "sealed; open", SizeClass.Small, readability: true);
            Shape("special.statue", "Statue", new[] { 9 }, "Board", "waiting; restored", SizeClass.Small, readability: true);
            Shape("special.bridge", "Bridge (repaired)", new[] { 9 }, "Board", "repaired", SizeClass.Small, readability: true);
            Shape("special.bridge_broken", "Bridge (broken)", new[] { 9 }, "Board", "broken", SizeClass.Small, readability: true);
            Shape("special.region", "Region marker (restore this whole area)", new[] { 9 }, "Board", "pending; done", SizeClass.Small, readability: true);

            // ---- Pods and slots ----
            Add("pod.card", "Spirit Pod (spec 005 §3.7)", new[] { 7, 8, 9, 12 }, "Tray", "exposed (bright, takes the tap); waiting in its column (muted); pressed (sunk)", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "a dark wooden frame 1.3 times as wide as tall (`mat.wood.dark`) around a cream panel tinted by the variant, the owner's icon of the variant (`tile.icon.*`) alone over its middle and the small outlined count at its bottom right corner (the owner's choice E, 2026-10-03); the sticker tile (`tile.candy.sticker`) stands in without the picture; a waiting pod shows the same parts muted (a lighter wash, a veiled frame, the icon at 0.7, a softer count)");
            Add("pod.state.locked", "Locked pod", new[] { 12 }, "Tray", "locked; unlocking", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "the wooden frame around a grey panel with a padlock and the softer count");
            Add("pod.state.mystery", "Mystery pod", new[] { 12 }, "Tray; slots", "hidden; revealing", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "the lilac mystery tile with a white ? (`tile.mystery`) and its count; it flips over to the variant tile in its slot");
            Add("pod.link", "Connected pods link", new[] { 12 }, "Tray", "pair; triple", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "a teal bar with a white rim and a light streak, riveted to each wooden frame of members side by side; on every member the link badge (UiRaster.LinkBadge: a white chain of two woven links on a disc of the group's color in the count badge's white ring) over its frame's top right corner, a smaller one at the \"+N\" disc of a column hiding a member, and a ring of the group's color pulsing round the partner after a tap that waits for it (spec 005 FR-043)");
            Add("pod.deck", "Source stack column (spec 005 FR-021; the owner's rule of 2026-10-03)", new[] { 7, 8, 9, 12 }, "Tray", "next pods (two on 16:9, three from 19.5:9); more below (+N); sliding up or down a row; emptied stack", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "the stack's pods one after another in a column, never on each other: the exposed pod in the top row and the next ones in the rows under it, each fully visible (`pod.card`, waiting look; a hidden mystery pod shows its ? and count, a locked one its padlock); the +N count badge on the last shown pod's top left corner; the pods slide up a row when the exposed one leaves and down when Return puts one back; a sunk parchment well for an emptied stack");
            Add("pod.count", "Pod and slot count", new[] { 7, 12, 13 }, "Pods; slots; jam row", "normal; dropping; dimmed", SizeClass.Icon, true, Launch, PlaceholderKind.Procedural, "small brown digits in a white outline, no \"x\": at a pod's bottom right corner over its icon; plain below a slot's tile");
            Add("slot.empty", "Empty Waiting Slot", new[] { 7, 13 }, "Slots", "empty", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "a cream plate pressed into the parchment with a light inner ring and a stitched dashed inner outline");
            Add("slot.state.working", "Working pod in a slot", new[] { 13 }, "Slots", "working; finishing", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "a raised cream plate with the variant's sticker tile and the plain count below it");
            Add("slot.state.stuck", "Stuck (waiting) pod in a slot", new[] { 13 }, "Slots", "stuck", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "the raised cream plate with the tile in grey, a softer count and the hourglass badge");
            Shape("slot.state.waiting", "Waiting mark (hourglass)", new[] { 13 }, "Slots", "waiting", SizeClass.Icon, readability: true);
            Shape("slot.state.jam_risk", "Jam-risk mark (!)", new[] { 13 }, "Slots", "risk", SizeClass.Icon, readability: true);
            Add("slot.state.locked", "Locked slot", new[] { 13 }, "Slots", "locked; opening", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "a grey raised plate with a padlock");
            Shape("slot.state.danger", "Danger slot frame (the last free usable slot)", new[] { 13 }, "Slots", "danger (4/5 used)", SizeClass.Small, readability: true);
            Add("slot.extra", "Extra slot (from the Extra Slot booster)", new[] { 13 }, "Slots", "added", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "a plate with a green \"+\" badge over its upper left corner");
            Add("slot.state.target", "Return target (a pod Return can take back)", new[] { 13 }, "Slots", "targeting", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "the selected booster's pulsing golden glow and ring around the plate");

            // ---- Boosters ----
            Shape("booster.extra_slot", "Booster: Extra Slot (the owner's picture `Icons/booster-extra_slot.png` replaces the drawn icon, spec 005 pictures.md D1)", new[] { 7, 8, 9, 10, 14, 16, 17 }, "Booster bar; jam sheet; Store; rewards; demos", "available; count; price; disabled", SizeClass.Small);
            Shape("booster.shuffle", "Booster: Shuffle (the owner's picture `Icons/booster-shuffle.png` replaces the drawn icon, pictures.md D2)", new[] { 7, 8, 9, 10, 14, 16, 17 }, "Booster bar; jam sheet; Store; rewards; demos", "available; count; price; disabled", SizeClass.Small);
            Shape("booster.return", "Booster: Return (the owner's picture `Icons/booster-return.png` replaces the drawn icon, pictures.md D3)", new[] { 7, 8, 9, 10, 14, 17 }, "Booster bar; jam sheet; Store; demos", "available; count; price; disabled; targeting", SizeClass.Small);
            Shape("booster.bloom_burst", "Booster: Bloom Burst (the owner's picture `Icons/booster-bloom_burst.png` replaces the drawn icon, pictures.md D4)", new[] { 9, 14, 17 }, "Booster bar; jam sheet; Store; demos", "available; count; price; disabled; targeting", SizeClass.Small);
            // Spec 005 §3.8: the colored icons are drawn from parts (GardenLook.BoosterIcon); the ids above are their one-color silhouettes.
            Shape("booster.extra_slot.disc", "Booster icon part: Extra Slot's blue disc", new[] { 10, 14, 17 }, "Booster tiles; jam choices; Store", "colored icon");
            Shape("booster.extra_slot.plus", "Booster icon part: Extra Slot's white plus", new[] { 10, 14, 17 }, "Booster tiles; jam choices; Store", "colored icon");
            Shape("booster.shuffle.a", "Booster icon part: Shuffle's orange arrow", new[] { 10, 14, 17 }, "Booster tiles; jam choices; Store", "colored icon");
            Shape("booster.shuffle.b", "Booster icon part: Shuffle's green arrow", new[] { 10, 14, 17 }, "Booster tiles; jam choices; Store", "colored icon");
            Shape("booster.bloom_burst.petals", "Booster icon part: Bloom Burst's pink petals", new[] { 10, 14, 17 }, "Booster tiles; jam choices; Store", "colored icon");
            Shape("booster.bloom_burst.center", "Booster icon part: Bloom Burst's yellow center", new[] { 10, 14, 17 }, "Booster tiles; jam choices; Store", "colored icon");
            Add("booster.tile", "Booster tile (spec 005 §3.7)", new[] { 7, 8, 9, 14 }, "Booster bar", "charges; price; selected; disabled; pressed", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "a cream squircle face raised on the buttons' wooden plate (spec 005 FR-047), grey when disabled; the count badge over its lower right corner, or the cost pill below it and a green + raised on its plate");

            // ---- UI kit ----
            Shape("ui.panel", "Rounded panel base (9-slice)", new[] { 4, 5, 6, 10, 11, 15, 16, 17 }, "Every card, button, pill and tile", "any tint", SizeClass.Small);
            Shape("ui.circle", "Disc (round buttons, badges, avatars)", new[] { 2, 3, 5, 7, 14 }, "Round buttons; badges; medals; avatars", "any tint", SizeClass.Icon);
            Shape("ui.ring", "Ring (highlights, profile frame)", new[] { 3, 7 }, "Highlights; entry marker; avatar frame", "any tint", SizeClass.Icon);
            Add("ui.button.primary", "Primary button (green, darker lower edge)", new[] { 2, 3, 4, 10, 11, 15, 16 }, "PLAY; NEXT; CLAIM; RESUME; CONTINUE; Free rescue", "normal; pressed; disabled", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "a glossy green face raised on its wooden plate (`ui.button.rim`, `ui.button.face.raised`; spec 005 FR-045): the gloss band and shine, volumetric label");
            Add("ui.button.secondary", "Secondary button (cream)", new[] { 4, 5, 10, 11, 15 }, "RESTART; SETTINGS; HOME; Restart; ×2 reward; Get +N; the Leaderboard page's Refresh", "normal; pressed; disabled", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "a cream face raised on its wooden plate (`ui.button.rim`, `ui.button.face.raised`; spec 005 FR-045), brown label and raised glyph");
            Add("ui.button.round", "Icon button, a cream face raised on a wooden plate (also the profile avatar)", new[] { 2, 3, 5, 6, 7, 11, 17 }, "Settings; Pause; close; the pages' back; edit; Daily Challenge; ‹ › arrows; the profile avatar (Home's header, the profile page)", "normal; pressed; avatar", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "a rounded square (corners 34% of the side; the owner, 2026-10-06, they were circles): the wooden plate (`ui.button.rim`, its border 10% of the side) and the cream face raised on it (`ui.button.face.raised`, spec 005 FR-044) with a raised brown glyph (`ui.glyph.raised`); the avatar: the picture filling a rounded square inside the plate's border (a soft green middle with the player's hero, `char.hero3d.bloom`, while it is missing), the profile frame and badge (`cosmetic.frame`, `cosmetic.badge`)");
            Add("ui.pill.level", "Level label of the gameplay top bar", Gameplay, "Gameplay top bar", "normal; super hard", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "a wooden sign with ivy (`ui.sign.wood`, `ui.sign.ivy`) and brown \"Level N\"; purple letters on Super Hard");
            Add("ui.pill.speed", "Fast-forward pill (3×)", Gameplay, "Gameplay top bar", "off; lit", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "the icon buttons' cream face raised on its wooden plate (`ui.button.rim`, `ui.button.face.raised`), wider, with only the `ui.fast` chevrons, raised (`ui.glyph.raised`); lit while on (a `garden.glow` halo, green chevrons)");
            Add("ui.pill.petals", "Petals balance pill", new[] { 2, 3, 17 }, "Home (centered in the header row, larger); the pages' headers", "with +; without +", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "a cream pill raised on its wooden plate (spec 005 FR-047) fitting its amount: the lotus inside its left end, the brown balance right after it and a round green + raised on its plate over its right end (`PetalsPillParts`); no decoration (the owner, 2026-10-06)");
            Add("ui.badge.hard", "HARD badge", new[] { 8 }, "Gameplay", "intro; steady", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "red glossy pill raised on its wooden plate (spec 005 FR-047)");
            Add("ui.badge.super_hard", "SUPER HARD badge", new[] { 9 }, "Gameplay", "intro; steady", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "purple raised sticker pill on a plate");
            Add("ui.badge.count", "Count badge (booster charges, +N on a stack)", new[] { 7, 12, 14 }, "Booster bar; tray", "count", SizeClass.Icon, false, Launch, PlaceholderKind.Procedural, "dark green disc with a white ring and white digits");
            // The Store, the Wardrobe, the Leaderboard and the Collection are pages since the owner's requests of 2026-10-04.
            Add("ui.card", "Popup card", new[] { 4, 11, 16 }, "Daily Reward; Pause; Milestone; Settings; Daily Challenge; No Ads; the purchase confirmation; Edit profile", "with close; without close", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "the wooden frame round the cream panel (`ui.card.frame`), the title on a wooden sign over its top edge (`ui.sign.wood`) with the pink lotus behind it (`ui.card.lotus`), the leaves and flower over two corners and the close button over the top-right corner, over a scrim (spec 005 FR-045)");
            Add("ui.card.frame", "Popup card's wooden frame and cream panel", new[] { 4, 10, 11, 16 }, "every popup card; the jam card", "normal", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "UiRaster.CardFrame (spec 005 FR-045): a frame of the buttons' plate laminate, 26 units on a 920-unit card, its grain along each member, rounding over at both edges, lit from the upper left, over a front side along the bottom, round a cream panel with a soft shadow under the frame's inner edge");
            Add("ui.card.lotus", "Lotus behind a popup's title sign", new[] { 4, 11, 16 }, "every popup card with a title", "normal", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "the owner's lotus (`currency.petal`'s picture) 2.3 times the sign's height, its middle at the sign's top so its petals rise above it; the drawn lotus while it is missing");
            Add("ui.card.purchase", "Purchase confirmation card (spec 005 FR-040): every purchase, for Petals or real money, asks first", new[] { 17 }, "Store (boosters, cosmetics, clearing styles, Petal packs, Remove Ads); Wardrobe; a booster bought in a level; the profile's avatars; the Remove Ads card", "Petals; real money (the store's sheet follows)", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "the popup card (`ui.card`, no close) with \"Confirm purchase\", the item's picture in a cream well, \"Buy … for … Petals?\", the cost pill (`ui.pill.cost`), a caption, the green Buy (`ui.button.primary`) and the cream Cancel (`ui.button.secondary`)");
            Add("ui.lotus_iris", "Lotus iris (spec 005 FR-039): the parchment cover closing on the middle of the screen through a round hole with a pink rim, the lotus popping in with \"Level N\" and a spinning ring of petals, then opening on the next level; the splash opens through it too", new[] { 1, 15 }, "The win's Next → the next level; the splash → the first screen", "closing; closed (the lotus, the ring, \"Level N\"); opening", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "UiRaster.IrisHole (`parchment.bottom` but for a round hole) scaled to the hole with plain `parchment.bottom` round it, a `lotus.fill` rim with a `lotus.line` edge, UiRaster.IrisGlow behind the lotus (`currency.petal`), twelve `fx.petals` and the text");
            Add("ui.spotlight", "Guided spotlight (spec 005 FR-035): the screen dimmed but for one lit place, a breathing glow ring round it, a parchment bubble with the message and a pointing hand on a forced step", Gameplay, "Gameplay: the Garden Entry (L1), the first tap (L1), the blocked entry (first time), each booster at its unlock", "tap to continue; forced (only the lit place takes the tap)", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "UiRaster.SpotlightScrim (`surface.scrim` at 0.72 with a soft rounded hole), a `garden.glow` ring, a parchment bubble (`mat.parchment`) with a tail and `ui.pointer`");
            Add("ui.sheet", "Jam card frame (spec 005 FR-022)", new[] { 10 }, "Jam", "popping in; open", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "a parchment card in the middle of the screen over the warm scrim, with a brown title and a soft brown subtitle (two lines when long), popping in");
            Add("ui.row", "List row (the Settings card, the Store and Leaderboard pages)", new[] { 5, 11, 17 }, "Settings; Store page; Leaderboard page", "normal; highlighted (You); unavailable", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "a raised cream slab (`ui.row.raised`); the own row green-tinted in a green rim with flowers over its top corners (spec 005 FR-047); a Leaderboard row's portrait a white face raised on its wooden plate with the `ui.person` glyph, and its name and score while offline light wood grooves pressed into it (`UiRaster.Groove`, spec 005 FR-048)");
            Add("ui.row.raised", "Raised cream slab of a row, a pill or a card", new[] { 5, 11, 17 }, "Settings rows; the dev row's pills; Store and Leaderboard rows; cost pills; toasts; the profile card; Home's teaser", "normal; the own row's green", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "UiRaster.RaisedRow (spec 005 FR-045, FR-047): the buttons' raised face without its plate in the light row cream (`set.row`, the own row `set.row.you`), its front side 6% of its height");
            Add("ui.tile.framed", "Tile in a thin wooden rim", new[] { 6, 17 }, "Profile stats and achievements; outfit cards (Store cosmetics, Wardrobe); the Collection's frames", "normal; pressed", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "UiRaster.ButtonPlate with a rim of `GardenLook.TileRimShare` (spec 005 FR-047, the owner's references of 2026-10-08) and the raised face in the row cream");
            Add("ui.settings.icon", "Settings row icon", new[] { 11 }, "Settings: Music (Unity), Sound, Haptics, Fast forward", "normal", SizeClass.Icon, false, Launch, PlaceholderKind.Procedural, "the owner's flower (Sound), leaf (Haptics) and violet bud (Music) icons, the raised `ui.fast` chevrons in `medal.gold` (Fast forward); the drawn symbols while the pictures are missing (the owner's mockup of 2026-10-08)");
            Add("ui.tab", "Tab", new[] { 17 }, "Store; Wardrobe", "selected; unselected", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "pills raised on their wooden plates (spec 005 FR-047): selected glossy green, the others light wood (`set.tan`)");
            Add("ui.toggle", "Toggle switch", Array.Empty<int>(), "Settings", "on; off", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "UiRaster.ToggleTrack and ToggleKnob (spec 005 FR-048, the owner's Settings mockup): a track with round ends pressed into the row, deeper under its upper edge and catching the light along its lower one (on: green, `set.green`, with a faint lighter check in a lighter disc in its left end; off: deeper wood, `set.tan.deep`, with a faint leaf pressed into its right end) and a round cream button, flat on top with its edge rounded off, 0.98 of the track's height over a soft shadow at the track's right end when on, its left end when off; in Settings 160 × 82 units (`CardLook.SettingsToggleBox`)");
            // Spec 005 §3.2 to §3.6: wooden signs and rims, jam choices, cost pills, the stone pedestal, the wooden wordmark.
            Add("ui.sign.wood", "Wooden sign (level label, win and banner titles, Home level plaque)", new[] { 2, 3, 7, 15, 17 }, "Gameplay top bar; win; Home; Store; Wardrobe", "plain; ivy; flowers; super hard letters", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "UiRaster.LaminateSign (spec 005 FR-045: the buttons' plate laminate, its edge rounding over, two nails) with brown embossed letters and a soft shadow");
            Shape("ui.sign.ivy", "Ivy cluster over a sign's ends (clovers with pointed leaflets, at the top and bottom corners; the owner's picture `Decor/ivy.png`, mirrored for the right end, replaces it, pictures.md D5)", new[] { 5, 6, 7, 17 }, "Gameplay level sign; the Store, Wardrobe, Leaderboard and Collection banners; wordmark", "left; right (mirrored)", SizeClass.Small);
            Add("ui.sign.flowers", "Flower clusters on the win and milestone signs (the owner's picture `Decor/flowers.png`, mirrored for the other end, replaces them, pictures.md D6)", new[] { 15, 16 }, "Win sign; milestone sign", "top-left; other end (mirrored)", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "lush clusters of five big leaves with veins and two white flowers at two corners (`ui.deco.garden`)");
            Add("ui.button.rim", "Light wood rim of the main buttons, wooden plate of the icon buttons", new[] { 2, 3, 5, 6, 7, 10, 11, 15, 16, 17 }, "PLAY; NEXT; RESUME; CLAIM; CONTINUE; Free rescue; the icon buttons, the speed pill and the profile avatar (the owner, 2026-10-06)", "normal; pressed", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "UiRaster.Plank (pale wood, only a thin deeper bottom band) behind the green face; under an icon button the wooden plate (UiRaster.ButtonPlate, spec 005 FR-044): a caramel laminate slab with its front side, its border 10% of the side rounding over, lit at the top, in a deeper outline, a groove and the raised face's soft shadow in its opening");
            Add("ui.button.face.raised", "Raised cream face of the icon buttons", new[] { 2, 3, 5, 6, 7, 8, 9, 11, 17 }, "Settings; Pause; close; the pages' back; edit; Daily Challenge; ‹ › arrows; the speed pill", "normal; pressed (sunk 3%); disabled (grey)", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "UiRaster.ButtonFace (spec 005 FR-044): a warm cream slab with a faint grain standing on the plate, its top's edge rounding down, lit from the upper left, over its front side in the set's lip");
            Add("ui.glyph.raised", "Raised glyph on a cream face", new[] { 2, 3, 5, 6, 7, 8, 9, 10, 11, 17 }, "the icon buttons' glyphs; the speed pill's chevrons; ‹ ›; Restart's ⟳; the ×2 offer", "normal; lit (speed pill)", SizeClass.Icon, false, Launch, PlaceholderKind.Procedural, "UiRaster.RaisedGlyph (spec 005 FR-044): the brown glyph's edge rounding over, lit from the upper left, over a soft shadow and a light emboss line, as if pressed into the cream");
            Add("ui.button.choice", "Jam choice button (icon above the label, cost pill below)", new[] { 10 }, "Jam sheet", "green; blue; pressed; disabled", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "a glossy green or blue face raised on its wooden plate (corners 22%; spec 005 FR-045) with the booster icon, a white outlined label and a cost pill");
            Add("ui.pill.cost", "Cost pill (lotus and price, Free, ×N)", new[] { 10, 14, 17 }, "Jam choices; booster tiles; Store", "price; free; charges", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "a cream pill raised like the rows (`ui.row.raised`), or on the Store's rows a button raised on its wooden plate with the main buttons' leaves (spec 005 FR-047): the lotus and a brown price, a green ▶ square and Free, or ×N");
            Add("ui.pedestal", "Stone pedestal under the heroes", new[] { 2, 3, 15, 16 }, "Win; milestone; Home; Wardrobe", "normal", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "UiRaster.Pedestal picture: a warm grey-beige ellipse-topped stone drum with block joints, a crack, moss tufts and a dark outline (the win stands on the owner's painted disc instead when `Backgrounds/win.jpg` exists)");
            Add("ui.logo.wood", "Wooden wordmark letters (the stand-in for the owner's logo; its leaves are the owner's `Decor/logo-leaves.png` when it exists, pictures.md D8)", new[] { 1, 2, 3 }, "Splash; Home", "full; compact", SizeClass.Large, false, Launch, PlaceholderKind.Text, "wordmark text in pale cream-yellow wood with a wood outline and extrusion, ivy clusters and a pink flower");
            // Spec 005 §4.5, §4.6: the Wardrobe look of the meta screens (the playtest's Store cosmetics) and the drawn Home stage.
            Add("ui.tab.family", "Family tab (Wardrobe; the Store's cosmetics)", new[] { 17 }, "Store cosmetics; Wardrobe", "selected (lighter, joined to the panel); unselected", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "cream tab with rounded top corners holding the family's 3D hero and its name; the selected one lighter and flowing into the panel below");
            Add("ui.card.clearing", "Clearing style card (the Store's Animations tab; spec 005 FR-038)", new[] { 17 }, "Store: Animations", "free pair; for sale (Buy); bought (Choose); chosen (check, Chosen); before L40 (cost pill, padlock)", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "the outfit card holding a live preview, looping all the time: a small board of 5 × 3 tiles with its arch and a slot, cleared in the style in a loop");
            Add("ui.button.clearing", "Clearing style card's action button (spec 005 FR-038 as amended on 2026-10-06)", new[] { 17 }, "Store: Animations", "Buy (with the price); Choose; Chosen", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "where the cost pill hangs, wider: the green Buy (`ui.button.primary`'s face) with \"Buy\", the lotus and the price; the cream Choose (`ui.button.secondary`'s face); Chosen: a flat cream plate with a green check and green letters");
            Add("ui.card.outfit", "Outfit card (Wardrobe; the Store's cosmetics)", new[] { 17 }, "Store cosmetics; Wardrobe", "normal; worn; for sale (cost pill); locked (padlock)", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "a cream card in a thin wooden rim (`ui.tile.framed`, spec 005 FR-047) with a beige picture well showing the hero in the item and the name below; the worn one green-tinted with a green border and a check badge (a glossy green ball, `UiRaster.Ball`, spec 005 FR-048, with a white check in a white ring); a locked one faded with a padlock badge (the switches' cream knob with the brown padlock)");
            Add("ui.fountain", "Lotus fountain of the drawn Home stage (the stand-in for the owner's Home diorama)", new[] { 2 }, "Home (early)", "normal", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "a small stone basin (`ui.pedestal`) with water, two lily pads and the pink lotus, between the heroes on the stone pedestal");
            Shape("ui.close", "Close glyph", new[] { 4, 5, 6, 11 }, "Cards", "normal");
            Shape("ui.pause", "Pause glyph", Gameplay, "Gameplay top bar", "normal");
            Shape("ui.restart", "Restart glyph (⟳)", new[] { 5, 10, 11 }, "Pause card; jam sheet; the Leaderboard page's Refresh", "normal");
            Shape("ui.settings", "Settings glyph (gear)", new[] { 2, 3, 11 }, "Home; Pause card", "normal");
            Shape("ui.chevron", "Chevron (opens a screen, turns a page)", new[] { 6, 17 }, "Daily Challenge card; ‹ › arrows (the Wardrobe, the Store and Collection pages)", "normal");
            Shape("ui.plus", "Plus glyph", new[] { 2, 3, 17 }, "Petals pill; + Slot", "normal");
            Shape("ui.check", "Check mark (done; the picked avatar, frame or badge)", new[] { 3 }, "Home Daily Challenge card (done today); the profile's edit card", "normal");
            Shape("ui.edit", "Pencil glyph (edit)", new[] { 2 }, "The profile page: the name's edit button", "normal");
            Shape("ui.play", "Play triangle, as tall as the letters (spec 003 FR-010)", new[] { 2, 3 }, "PLAY on Home", "normal; pressed");
            Shape("ui.fast", "Fast-forward glyph (three chevrons) of the speed pill (spec 005)", Gameplay, "Gameplay top bar", "normal");
            Shape("ui.back", "Back arrow glyph (spec 005)", new[] { 5, 6, 17 }, "The pages' back: Wardrobe; Store; Leaderboard; Collection", "normal");
            Shape("ui.deco.garden", "Leaves and a white flower on the main buttons and Home's Petals pill (spec 003 FR-011a; the owner's picture `Decor/button-leaves.png`, turned half way for the bottom right, replaces them, pictures.md D7); since spec 005 FR-047 also the owner's flowers (`Decor/flowers.png`, pictures.md D6) over the pages' frame corners, the profile's tiles and wooden avatar frame, the own Leaderboard row and the Wardrobe's name card, and the leaves on the Store's price buttons", new[] { 2, 3, 5, 11, 15, 16, 17 }, "PLAY; RESUME; NEXT; CONTINUE; CLAIM; Home's Petals pill; the pages' frames; the Store's prices", "top-left; top-right (mirrored); bottom-left (turned); bottom-right (turned); on the pill, larger for its height", SizeClass.Small);
            Shape("ui.gift", "Gift (milestone teaser)", new[] { 3 }, "Home", "normal; ready", SizeClass.Small);
            Shape("ui.trophy", "Trophy (Get +N; the bottom menu's Leaderboard stand-in)", new[] { 4 }, "Daily Reward; bottom menu (while `Icons/nav-leaderboard.png` is missing)", "normal", SizeClass.Small);
            Shape("ui.medal", "Medal (ranks 1–3)", new[] { 5 }, "Leaderboard page", "gold; silver; bronze", SizeClass.Small);
            Shape("ui.ad", "Rewarded-ad mark (video)", new[] { 4, 10, 15 }, "Get +N; Free rescue; ×2 reward; free booster", "normal");
            Shape("ui.shirt", "Wardrobe glyph (the bottom menu's stand-in)", new[] { 3 }, "Bottom menu (while `Icons/nav-wardrobe.png` is missing)", "normal");
            Shape("ui.grid", "Collection glyph (the bottom menu's stand-in)", new[] { 3 }, "Bottom menu (while `Icons/nav-collection.png` is missing)", "normal");
            Shape("ui.sun", "Daily Challenge glyph", new[] { 3 }, "Home Daily Challenge card", "normal; done", SizeClass.Small);
            Shape("ui.person", "Player avatar placeholder", new[] { 5 }, "Leaderboard page; profile", "any tint", SizeClass.Small);
            Shape("ui.lock", "Padlock", new[] { 9, 12, 13, 14 }, "Locked pods, slots and cells; locked boosters", "closed; opening", readability: true);
            Shape("ui.star", "Star (Hard label, badge)", new[] { 8 }, "Difficulty intro; badges", "normal");
            Shape("ui.star2", "Double star (Super Hard label, marker)", new[] { 9 }, "Difficulty intro; markers", "normal");
            Shape("ui.cross", "Ignore mark (a pod ignores another variant)", Array.Empty<int>(), "Variant demo (spec 001 FR-071)", "normal");
            Shape("ui.pointer", "Tutorial pointing hand", Array.Empty<int>(), "Demos", "tap; hold", SizeClass.Small);
            // Spec 005 §4.3 and §4.4: the jam's slot row and the reward pills of the win and the milestone.
            Add("ui.jam.slots", "Jam sheet: the inset row of the Waiting Slots' contents", new[] { 10 }, "Jam sheet", "jammed (all full); stuck (free and locked slots too)", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "a sunk parchment well with each slot's sticker tile (`tile.candy.sticker`) and its brown count; free slots as small dashed plates, locked ones with the padlock");
            Add("ui.pill.reward", "Reward pill (win, milestone)", new[] { 15, 16 }, "Win; milestone", "counting up; steady", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "the cream cost pill (`ui.pill.cost`), bigger, with the lotus and \"+N\" counting up; on the milestone each reward on a cream tile with its amount in the pill");

            // Spec 005 FR-030 (the owner's bottom menu, the wooden variant, 2026-10-04): the bar, its medallion and the
            // owner's five icons (OwnerPictures.NavIcon), on Home and the four pages.
            Add("ui.nav.bar", "Bottom menu: the wooden bar across the screen's bottom (spec 005 FR-030)", new[] { 2, 3, 5, 6, 17 }, "Home; the Store, Wardrobe, Leaderboard and Collection pages", "its five places, always shown (a locked one with its padlock badge); grooves between them", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "UiRaster.NavBar picture: a warm brown plank (`wood.dark_top` to `wood.dark`, grained, rounded ends) from 0.14 W above the safe bottom to the screen's bottom, thin carved grooves between the places, no vines at its ends");
            Add("ui.nav.medallion", "Bottom menu: the raised round medallion of the active place", new[] { 2, 3, 5, 6, 17 }, "Home; the Store, Wardrobe, Leaderboard and Collection pages", "Home; Shop; Wardrobe; Leaderboard; Collection", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "UiRaster.NavMedallion picture: a lighter honey wood disc in a darker wooden rim, rising 0.03 W above the plank, with short vines, eight leaves and two small white flowers on its rim and a soft shadow under it");
            foreach (NavPlace place in BottomNav.Order)
            {
                string glyph = BottomNav.Fallback(place).ShapeId;
                // Home is always open; the other places can be locked (a padlock badge on the plank, their notice).
                bool lockable = place != NavPlace.Home;
                Add(BottomNav.Slot(place), "Bottom menu icon: " + place + " (the owner's picture `Icons/" + OwnerPictures.NavIcon(place) + ".png`, spec 005 pictures.md D" + (9 + IndexOf(BottomNav.Order, place)) + ")", new[] { 2, 3, 5, 6, 17 }, "Bottom menu (on the plank; in the medallion when active)" + (lockable ? "; locked notice" : string.Empty), "on the plank; in the medallion; pressed" + (lockable ? "; locked (padlock badge)" : string.Empty), SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "the `" + glyph + "` glyph in its color over a darker outline until the picture exists");
            }

            // The owner's request of 2026-10-04: every place always shows; a locked one carries a padlock badge, and its
            // page says from which level it is available.
            Add("ui.nav.lock", "Bottom menu: the padlock badge of a locked place", new[] { 2, 5, 6, 17 }, "Bottom menu (a locked place's icon on the plank); locked notice", "locked; pressed (squashes with its icon)", SizeClass.Icon, false, Launch, PlaceholderKind.Procedural, "the outfit cards' padlock badge (`Kit.LockBadge`): the switches' round cream button (`UiRaster.ToggleKnob`, spec 005 FR-048) in a `cream.line` ring with the brown `ui.lock`, over a soft shadow, 0.34 of the icon's side at its lower right inside the plank's band");
            Add("ui.locked.notice", "Locked notice: \"Available from level N\" on a locked place's page", new[] { 5, 6, 17 }, "The Store, Wardrobe, Leaderboard and Collection pages (before their unlock)", "Shop; Wardrobe; Leaderboard; Collection", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "the place's owner icon (or its stand-in glyph) 0.4 of the area's width with the padlock badge on its lower right, then \"Available from level N\" in `type.title` `ink.brown` and \"Keep playing to unlock it!\" in `type.body` `ink.brown_soft`, centered");

            // The owner's Home promo scenes (spec 005 FR-032, pictures.md D14–D22, `HomePromo`).
            Add(OwnerPictures.AvatarSlot, "Profile avatar picture (the owner's `Avatars/*.jpg`, pictures.md I; spec 005 FR-037): it fills the avatar's whole disc inside a thin `cream.line` ring, on the cream lip (`AvatarLook`; the owner, 2026-10-06)", new[] { 2, 3, 5 }, "Home's avatar button; the profile page; its edit card; the player's own leaderboard row", "each of the 14 avatars; owned; for sale (price pill); picked (check)", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "the profile hero (`char.hero3d.bloom`) on the soft green middle while the picture is missing");
            Add("ui.achievement", "Achievement tile (Green Thumb, Picture Keeper, Daily Gardener; spec 005 FR-037)", new[] { 2 }, "The profile page's Achievements", "before bronze (padlock); bronze; silver; gold (check)", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "a cream tile in a thin wooden rim with flowers over two corners (`ui.tile.framed`, spec 005 FR-047) with the trophy (`ui.trophy`) in its tier's medal color (`medal.bronze`, `medal.silver`, `medal.gold`; faded before bronze) and the count toward the next tier, the name under it");
            Add("ui.promo.no_ads", "Home promo scene: No Ads (the owner's layers `Decor/promo-noads-*.png`: the stand, Sprig, the crossed AD sign, the lotus)", new[] { 2, 3 }, "Home (left, under the logo, until Remove Ads is owned); the Remove Ads card", "idle; attention (Sprig pushes the sign off, a lotus blooms, both come back); pressed", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "the label \"No Ads\" on a wooden sign (`ui.sign.wood`) until the pictures exist");
            Add("ui.promo.daily", "Home promo scene: the Daily Reward (the owner's layers `Decor/promo-daily-*.png`: the stand, the album closed and open, the flower stamp, the petals)", new[] { 3 }, "Home (right, under the logo, from the Daily Reward's unlock)", "idle; attention while the reward waits (the album opens, the stamp presses, petals burst); pressed", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "the label \"Daily\" on a wooden sign (`ui.sign.wood`) until the pictures exist");

            // ---- Materials (spec 005 FR-006, contracts/look.md §2) ----
            Add("mat.wood.light", "Light wood (signs, button rims)", new[] { 2, 3, 7, 15 }, "Signs; main button rims; wordmark", "any size; grain by seed", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "UiRaster.Plank, light tone");
            Add("mat.wood.dark", "Dark wood (pod frames)", new[] { 7, 12 }, "Pods", "exposed; waiting (veiled); locked", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "UiRaster.Frame, dark tone");
            Add("mat.stone", "Stone blocks (board border, pedestal)", new[] { 7, 15 }, "Board border; pedestal", "any size; moss by seed", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "UiRaster.Stone and Pedestal (warm sandy stone, smooth, a few soft moss tufts)");
            Add("mat.parchment", "Parchment (cards, the pages' panels, sheet, tray, slot band)", new[] { 4, 5, 6, 10, 11, 17 }, "Cards; the Store, Leaderboard and Collection pages' panels; jam sheet; tray; slot band; toasts", "any size", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "parchment gradient with a warm aged edge band, a thin brown outline and a thin inner line");

            // ---- Currency and rewards ----
            Shape("currency.petal", "Petals symbol (soft currency): a pink lotus (spec 005; the owner's picture `Icons/" + OwnerPictures.CurrencyLotus + ".png` replaces the drawn lotus)", new[] { 2, 3, 4, 10, 15, 16, 17 }, "Petals pill; rewards; costs; prices; badges", "small; large", SizeClass.Icon);
            Shape("currency.petal.front", "Lotus part: the front petals (center and sides) and the base", new[] { 2, 3, 4, 10, 15, 16, 17 }, "Wherever the lotus shows", "small; large", SizeClass.Icon);
            Shape("currency.petal.tips", "Lotus part: the near-white petal middles", new[] { 2, 3, 4, 10, 15, 16, 17 }, "Wherever the lotus shows", "small; large", SizeClass.Icon);
            Shape("currency.reward_basket", "Reward basket (Daily Reward; the bottom menu's Shop stand-in)", new[] { 4 }, "Daily Reward; bottom menu (while `Icons/nav-shop.png` is missing)", "day 1–7", SizeClass.Medium);
            Add("currency.petal_pile", "Pile of Petals (big rewards)", new[] { 4, 16 }, "Daily Reward; Milestone", "small; large", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "a cluster of Petal symbols");

            // ---- Collection ----
            Add("collection.frame", "Collection picture frame", new[] { 6 }, "The Collection page's grid (three to a row, as large as fit) and detail", "normal; pressed; new", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "a cream tile in a thin wooden rim (`ui.tile.framed`, spec 005 FR-047) round a beige well holding the finished picture");
            Add("collection.detail_frame", "Collection detail: a picture large on the Collection page", new[] { 6 }, "The Collection page's detail (the back returns to the grid)", "normal", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "the picture in its cream frame (`collection.frame`) up to 0.8 W, centered over its name (`type.title`) and \"Completed at Level N\" (`type.body`)");

            // ---- Cosmetics ----
            Shape("cosmetic.sprout", "Hat: Sprout", new[] { 16 }, "Wardrobe; walkers; Home hero; milestone rewards", "worn; preview");
            Shape("cosmetic.cap", "Hat: Cap", new[] { 16 }, "Wardrobe; walkers; Home hero; milestone rewards", "worn; preview");
            Shape("cosmetic.brim", "Hat: Brim hat", new[] { 16 }, "Wardrobe; walkers; Home hero; milestone rewards", "worn; preview");
            Shape("cosmetic.crown", "Hat: Crown", Array.Empty<int>(), "Wardrobe; walkers; Home hero", "worn; preview", priority: Later);
            Shape("cosmetic.nightcap", "Hat: Nightcap", Array.Empty<int>(), "Wardrobe; walkers; Home hero", "worn; preview", priority: Later);
            Shape("cosmetic.sparkle", "Trail: Sparkle", Array.Empty<int>(), "Wardrobe; walkers", "worn; preview", priority: Later);
            Shape("cosmetic.swirl", "Trail: Swirl", Array.Empty<int>(), "Wardrobe; walkers", "worn; preview", priority: Later);
            Shape("cosmetic.wink", "Expression: Wink", Array.Empty<int>(), "Wardrobe; walkers", "worn; preview", priority: Later);
            Shape("cosmetic.smile", "Expression: Smile", Array.Empty<int>(), "Wardrobe; walkers", "worn; preview", priority: Later);
            Shape("cosmetic.stars", "Expression: Star eyes", Array.Empty<int>(), "Wardrobe; walkers", "worn; preview", priority: Later);
            Shape("cosmetic.sleepy", "Expression: Sleepy", Array.Empty<int>(), "Wardrobe; walkers; stuck pods", "worn; preview");
            Shape("cosmetic.spots", "Skin: Spots", Array.Empty<int>(), "Wardrobe; pods; walkers", "on each family", priority: Later);
            Shape("cosmetic.stripes", "Skin: Stripes", Array.Empty<int>(), "Wardrobe; pods; walkers", "on each family", priority: Later);
            Shape("cosmetic.petals", "Skin: Petals", Array.Empty<int>(), "Wardrobe; pods; walkers", "on each family", priority: Later);
            Shape("cosmetic.speckles", "Skin: Speckles", Array.Empty<int>(), "Wardrobe; pods; walkers", "on each family", priority: Later);
            Shape("cosmetic.frame", "Profile frame", new[] { 2, 3, 5 }, "Home's profile avatar; own leaderboard row; Wardrobe (the profile avatar)", "each frame item", SizeClass.Small);

            // The five drawn profile frames, free from Level 1 (spec 005 FR-037 as amended 2026-10-06; ProfileFrames,
            // UiRaster.ProfileFrame): each a picture 1.125 of the avatar in the wood rim's place, its band over the picture's
            // rounded-square edge, with a soft shadow (rounded squares since the owner's requests of 2026-10-06; they were
            // rings over the disc's edge).
            const string FrameUse = "Home's profile avatar; the profile page; its edit card (Frame tab); Wardrobe (the profile avatar)";
            const string FrameStates = "on the avatar; in the edit card's Frame tab (picked: green disc and check)";
            Add("cosmetic.frame.wood_ring", "Profile frame: Wooden Frame (free from Level 1)", new[] { 2, 3, 5 }, FrameUse, FrameStates, SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "UiRaster.ProfileFrame picture: a rounded-square band in the buttons' plate laminate (spec 005 FR-047), rounding over at both edges, lit from the upper left, the plate's `wood.line` outline, four brass nails (`medal.gold`) at its corners; on the profile page with flowers over two corners");
            Add("cosmetic.frame.leaf_ring", "Profile frame: Leaf Frame (free from Level 1)", new[] { 2, 3, 5 }, FrameUse, FrameStates, SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "UiRaster.ProfileFrame picture: a green vine (`garden.leaf_3`, `garden.leaf_line`) round the rounded-square disc with twenty almond leaves in the three garden greens, all turning one way, out and in by turns");
            Add("cosmetic.frame.flower_wreath", "Profile frame: Flower Wreath (free from Level 1)", new[] { 2, 3, 5 }, FrameUse, FrameStates, SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "UiRaster.ProfileFrame picture: two twisted twigs (`wood.dark`) with sixteen small leaves and eight five-petal blossoms, pink (`lotus.fill`) at the sides' middles and white (`garden.flower`) at the corners, golden middles");
            Add("cosmetic.frame.stone_ring", "Profile frame: Stone Frame (free from Level 1)", new[] { 2, 3, 5 }, FrameUse, FrameStates, SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "UiRaster.ProfileFrame picture: twelve mottled blocks of sandy stone, one bent round each corner (`stone.top` to `stone.face`, a `stone.lip` side away from the light, `stone.line` outlines) on dark mortar, two with a tuft of moss (`stone.moss`)");
            Add("cosmetic.frame.golden_ribbon", "Profile frame: Golden Ribbon (free from Level 1)", new[] { 2, 3, 5 }, FrameUse, FrameStates, SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "UiRaster.ProfileFrame picture: a gold satin band (`medal.gold`, lit to `ray.light`) wound round in eighteen folds, a gold star on top and a pink bow (`lotus.fill`, `lotus.line`) at the bottom");
            Shape("cosmetic.badge", "Profile badge (incl. level badges)", new[] { 2, 3, 5 }, "Home's profile avatar; Wardrobe (the profile avatar)", "each badge item; level N", SizeClass.Small);
            Shape("cosmetic.marker", "Leaderboard marker (incl. level markers)", new[] { 5 }, "Own leaderboard row; Wardrobe", "each marker item; level N", SizeClass.Small);

            // ---- Effects ----
            Shape("fx.sparkle", "Sparkle", new[] { 7, 15 }, "Clears; win shine; burst", "small; large", SizeClass.Icon);
            Shape("fx.petal_burst", "Petal burst", new[] { 15, 16 }, "Win; milestone; rewards", "burst", SizeClass.Icon);
            Shape("fx.droplet", "Droplets (Drop-family clears)", new[] { 7, 8, 9 }, "Board: tiles restored by Drop Bloomlings", "splash", SizeClass.Icon);
            Add("fx.rays", "Light rays behind the celebrating heroes", new[] { 15, 16 }, "Win; milestone", "slowly turning", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "ten soft ray-light wedges from the pedestal");
            Shape("fx.petals", "Falling petals of the win", new[] { 15, 16 }, "Win; milestone", "drifting; swaying", SizeClass.Icon);
            Add("fx.confetti", "Confetti", new[] { 15, 16 }, "Win; milestone", "fall", SizeClass.Icon, false, Launch, PlaceholderKind.Procedural, "small rotating squares in level colors");
            Add("fx.puff", "Puff (a pod leaves its slot)", new[] { 13 }, "Slots", "puff", SizeClass.Icon, false, Launch, PlaceholderKind.Procedural, "expanding fading discs");
            Add("fx.shuffle_swirl", "Shuffle swirl", new[] { 14 }, "Tray", "swirl", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "pods spinning in place");
            Add("fx.burst", "Bloom Burst blast", new[] { 9, 14 }, "Board", "blast", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "pulsing targets and sparkles");
            Add("fx.win_shine", "Finished picture shine", new[] { 15 }, "Win", "sweep", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "a light band sweeping the picture");

            // The board's clearing styles (spec 005 FR-038; ClearLook, contracts/look.md §6.12): the walkers, their tile and its last leg.
            Add("fx.clear.blossom", "Clearing style Blossom (free)", new[] { 7 }, "Board: Levels 1–10 and odd levels; the Store's preview", "walk; the tile sinks turning; a flower opens; it fades into the picture; neighbours sway", SizeClass.Medium, true, Launch, PlaceholderKind.Procedural, "the walker hops once and sinks into its tile; a five-petal flower (white rim, the variant's lighter color, a golden middle) opens with an overshoot and fades with a sparkle");
            Add("fx.clear.munchers", "Clearing style Munchers (free)", new[] { 7 }, "Board: even levels from 12; the Store's preview", "walk; climb; three bites with crumbs; gulp; waddle home full; hop into the arch", SizeClass.Medium, true, Launch, PlaceholderKind.Procedural, "the walker sits on its tile, which shrinks from the top in three bites; small rounded crumbs in the variant color fly and fall; it walks home wider and lower");
            Add("fx.clear.fireflies", "Clearing style Fireflies (bought)", new[] { 7, 17 }, "Board (when chosen); the Store's preview", "walk; the tile glows; it breaks into fireflies; they hover and swarm to the slot", SizeClass.Medium, true, Later, PlaceholderKind.Procedural, "twelve golden dots with a soft glow and a three-dot trail, twinkling, on curves to the slot");
            Add("fx.clear.bubbles", "Clearing style Bubbles (bought)", new[] { 7, 17 }, "Board (when chosen); the Store's preview", "walk; blow a bubble round the tile; float on a wave to the slot; pop", SizeClass.Medium, true, Later, PlaceholderKind.Procedural, "a pale glass disc with a pink rainbow rim, a white rim and highlights, wobbling, the tile turning inside; a ring and droplets as it pops");
            Add("fx.clear.pushers", "Clearing style Pushers (bought)", new[] { 7, 17 }, "Board (when chosen); the Store's preview", "walk; step behind the tile; push it home tumbling a cell at a time; it hops from the arch into the slot", SizeClass.Medium, true, Later, PlaceholderKind.Procedural, "the tile turns a quarter and lifts a little on each cell, landing with a squash, its shadow under it; the walker leans in behind");
            Add("fx.clear.fireworks", "Clearing style Fireworks (bought)", new[] { 7, 17 }, "Board (when chosen); the Store's preview", "walk; the tile swells white; it pops; four sparkles arc to the slot", SizeClass.Medium, true, Later, PlaceholderKind.Procedural, "a white flash and a ring of dots, then sparkles (fx.sparkle) with a colored glow on arcs to the slot");
            Add("fx.clear.parade", "Clearing style Confetti Parade (bought)", new[] { 7, 17 }, "Board (when chosen); the Store's preview", "small walkers with a dot trail; two hops on the tile; squash and stretch; a pop into confetti and a ring", SizeClass.Medium, true, Later, PlaceholderKind.Procedural, "ten rotating confetti strips (gold, the variant color, pink) with a white edge and a white ring");

            // ---- Typography ----
            Add("font.display", "Display font (rounded, bold): titles, buttons, pills, wordmark", new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 14, 15, 16, 17 }, "Every screen", "bold; outlined; volumetric on colored faces", SizeClass.Icon, true, Launch, PlaceholderKind.BundledFont, "Nunito ExtraBold (SIL OFL 1.1), `UI/Fonts/Resources/Nunito-ExtraBold.ttf`");
            Add("font.body", "Body font: rows, captions, numbers", new[] { 3, 4, 5, 6, 10, 17 }, "Every screen", "regular; bold digits", SizeClass.Icon, true, Launch, PlaceholderKind.BundledFont, "Nunito SemiBold (SIL OFL 1.1), `UI/Fonts/Resources/Nunito-SemiBold.ttf`");

            // ---- Audio ----
            Add("audio.music.daylight_garden", "Music: Daylight Garden", Gameplay, "Gameplay; Home", "loop", SizeClass.Audio, false, Launch, PlaceholderKind.Synth, "none (silence); cues only");
            Add("audio.music.pond", "Music: Pond", Gameplay, "Gameplay", "loop", SizeClass.Audio, false, Later, PlaceholderKind.Synth, "none (silence); cues only");
            Add("audio.music.orchard", "Music: Orchard", Gameplay, "Gameplay", "loop", SizeClass.Audio, false, Later, PlaceholderKind.Synth, "none (silence); cues only");
            Add("audio.music.moonlit_garden", "Music: Moonlit Garden", Gameplay, "Gameplay", "loop", SizeClass.Audio, false, Later, PlaceholderKind.Synth, "none (silence); cues only");
            foreach ((string cue, string title, string use) in Cues)
            {
                Add("audio.cue." + cue, "Sound: " + title, Array.Empty<int>(), use, "one-shot", SizeClass.Audio, false, Launch, PlaceholderKind.Synth, "synthesized tone");
            }

            return list;
        }

        private static int IndexOf(IReadOnlyList<NavPlace> places, NavPlace place)
        {
            for (int i = 0; i < places.Count; i++)
            {
                if (places[i] == place)
                {
                    return i;
                }
            }

            return -1;
        }

        private static IReadOnlyList<string> Split(string text) =>
            text.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries).Select(s => s.Trim()).Where(s => s.Length > 0).ToArray();
    }
}
