using System;
using System.Collections.Generic;
using System.Linq;
using Bloomlings.Core.Variants;

namespace Bloomlings.Client.UI.Design
{
    /// <summary>The asset categories of FR-029.</summary>
    public enum AssetCategory
    {
        Brand,
        Background,
        Character,
        VariantSymbol,
        BoardTile,
        Special,
        PodSlot,
        Booster,
        UiKit,

        /// <summary>The reference look's materials (spec 005 FR-006): wood, stone, parchment.</summary>
        Material,
        Currency,
        CollectionFrame,
        Cosmetic,
        Effect,
        Typography,
        Audio,
    }

    /// <summary>The size class of an asset (data-model "AssetSlot").</summary>
    public enum SizeClass
    {
        /// <summary>Up to 96 px.</summary>
        Icon,

        /// <summary>Up to 192 px.</summary>
        Small,

        /// <summary>Up to 512 px.</summary>
        Medium,

        /// <summary>Up to 1024 px.</summary>
        Large,

        /// <summary>Full screen.</summary>
        Screen,

        /// <summary>A sound or music file.</summary>
        Audio,
    }

    /// <summary>Whether an asset is needed for launch.</summary>
    public enum AssetPriority
    {
        Launch,
        Later,
    }

    /// <summary>How the game stands in for the asset today.</summary>
    public enum PlaceholderKind
    {
        /// <summary>A <see cref="ShapeLibrary"/> shape with the slot's id.</summary>
        Shape,

        /// <summary>Drawn in code from tokens (backdrops, tile shading, cards, effects).</summary>
        Procedural,

        /// <summary>Text in the system font (the wordmark).</summary>
        Text,

        /// <summary>A synthesized sound (<c>ToneSynth</c>).</summary>
        Synth,

        /// <summary>The platform's bold or regular sans-serif.</summary>
        SystemFont,

        /// <summary>A font file bundled with the game (spec 003: Nunito, SIL OFL 1.1).</summary>
        BundledFont,

        /// <summary>Not drawn inside the game (the app icon): the platform default for now.</summary>
        External,

        /// <summary>A picture generated by <c>tools/artgen</c> and committed as the project's own art (spec 004).</summary>
        Generated,
    }

    /// <summary>
    /// One needed art or audio asset and the placeholder standing in for it (contracts/asset-slots.md). The inventory
    /// document is generated from these entries.
    /// </summary>
    public sealed record AssetSlot(
        string Id,
        AssetCategory Category,
        string Title,
        IReadOnlyList<int> Frames,
        IReadOnlyList<string> UsedIn,
        IReadOnlyList<string> States,
        SizeClass Size,
        bool Readability,
        AssetPriority Priority,
        PlaceholderKind Kind,
        string Placeholder);

    /// <summary>
    /// The registry of every asset slot (research R10, FR-029, FR-030). Every placeholder the Unity client or the full
    /// playtest draws or plays resolves to a slot here, and every slot is used somewhere (SC-003, both ways): the
    /// client tests and the preview tool check this. <c>dotnet run --project playtest/preview -- --inventory</c> writes
    /// <c>specs/002-ux-design-board/asset-inventory.md</c> from it. Engine-free.
    /// </summary>
    public static class AssetSlots
    {
        // Declared before All: static initializers run in order, and Build() reads these.
        private static readonly int[] Gameplay = { 7, 8, 9 };

        /// <summary>The sound cues (<c>SoundCue</c>, lowercase) and where they play.</summary>
        public static IReadOnlyList<(string Cue, string Title, string Use)> Cues { get; } = new[]
        {
            ("click", "button click", "Every button"),
            ("tap", "pod committed", "Tray"),
            ("refused", "refused tap", "Tray"),
            ("clear", "tile restored", "Board"),
            ("poddone", "pod finished", "Slots"),
            ("key", "key collected", "Board"),
            ("special", "special triggered", "Board"),
            ("booster", "booster used", "Booster bar"),
            ("jam", "jam", "Jam sheet"),
            ("win", "win", "Win"),
        };

        /// <summary>The id prefixes of each category (contracts/asset-slots.md, "Id scheme").</summary>
        public static IReadOnlyDictionary<string, AssetCategory> Prefixes { get; } = new Dictionary<string, AssetCategory>(StringComparer.Ordinal)
        {
            ["brand."] = AssetCategory.Brand,
            ["bg."] = AssetCategory.Background,
            ["char."] = AssetCategory.Character,
            ["symbol."] = AssetCategory.VariantSymbol,
            ["tile."] = AssetCategory.BoardTile,
            ["board."] = AssetCategory.BoardTile,
            ["special."] = AssetCategory.Special,
            ["pod."] = AssetCategory.PodSlot,
            ["slot."] = AssetCategory.PodSlot,
            ["booster."] = AssetCategory.Booster,
            ["ui."] = AssetCategory.UiKit,
            ["icon."] = AssetCategory.UiKit,
            ["mat."] = AssetCategory.Material,
            ["currency."] = AssetCategory.Currency,
            ["collection."] = AssetCategory.CollectionFrame,
            ["cosmetic."] = AssetCategory.Cosmetic,
            ["fx."] = AssetCategory.Effect,
            ["font."] = AssetCategory.Typography,
            ["audio."] = AssetCategory.Audio,
        };

        public static IReadOnlyList<AssetSlot> All { get; } = Build();

        private static readonly Dictionary<string, AssetSlot> ById = All.ToDictionary(s => s.Id, StringComparer.Ordinal);

        public static bool Has(string id) => ById.ContainsKey(id);

        public static AssetSlot? Find(string id) => ById.TryGetValue(id, out AssetSlot? slot) ? slot : null;

        /// <summary>The category an id's prefix belongs to, or null for an unknown prefix.</summary>
        public static AssetCategory? CategoryOf(string id)
        {
            foreach (KeyValuePair<string, AssetCategory> prefix in Prefixes)
            {
                if (id.StartsWith(prefix.Key, StringComparison.Ordinal))
                {
                    return prefix.Value;
                }
            }

            return null;
        }

        private static List<AssetSlot> Build()
        {
            var list = new List<AssetSlot>();

            void Add(string id, string title, int[] frames, string usedIn, string states, SizeClass size, bool readability, AssetPriority priority, PlaceholderKind kind, string placeholder)
            {
                AssetCategory category = CategoryOf(id) ?? throw new InvalidOperationException("Unknown asset slot prefix: " + id);
                list.Add(new AssetSlot(id, category, title, frames, Split(usedIn), Split(states), size, readability, priority, kind, placeholder));
            }

            void Shape(string id, string title, int[] frames, string usedIn, string states, SizeClass size = SizeClass.Icon, bool readability = false, AssetPriority priority = AssetPriority.Launch) =>
                Add(id, title, frames, usedIn, states, size, readability, priority, PlaceholderKind.Shape, "shape `" + id + "`");

            const AssetPriority Launch = AssetPriority.Launch;
            const AssetPriority Later = AssetPriority.Later;

            // ---- Brand ----
            Add("brand.wordmark", "Bloomlings wordmark (logo): the owner's picture `Brand/logo.png` (spec 005 pictures.md C1)", new[] { 1, 2, 3 }, "Splash; Home", "full; compact", SizeClass.Large, false, Launch, PlaceholderKind.Text, "the wooden letters `ui.logo.wood` until the picture exists");
            Add("brand.tagline", "Tagline \"Small friends. Big gardens.\" (the owner's optional picture `Brand/tagline.png`, spec 005 pictures.md C2)", Array.Empty<int>(), "Splash; Home", "full", SizeClass.Medium, false, Later, PlaceholderKind.External, "none yet: neither build shows a tagline; the slot keeps the picture's place for later");
            Add("brand.splash_art", "Splash illustration: the garden with the logo and the four families' heroes around the lotus fountain", new[] { 1 }, "Splash", "portrait; tall-phone crop", SizeClass.Screen, false, Launch, PlaceholderKind.Generated, "the owner's layered Home with the logo and the four animated heroes rising in (spec 005 FR-028; their motion carries on into Home); without the pictures, the drawn garden with the four still 3D heroes around the drawn lotus fountain");
            Add("brand.app_icon", "App icon", Array.Empty<int>(), "Launcher; store listing", "Android adaptive (foreground, background); iOS set", SizeClass.Medium, false, Launch, PlaceholderKind.External, "platform default icon");

            // ---- Backgrounds ----
            Add("bg.theme.daylight_garden", "Gameplay backdrop: Daylight Garden (levels 1–99 and every fourth band)", Gameplay, "Gameplay", "tall; short", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "procedural lush garden (spec 005 §4.2, FR-020: grass patches, fine blades and lighter paths; a deep `foliage.*` hedge, bushes and big leaves along the edges; many pink, white, orange and yellow flowers, big ones at the edges; a soft vignette) in fresh green until `Backgrounds/gameplay-daylight.png` exists (spec 005 pictures.md B2)");
            Add("bg.theme.pond", "Gameplay backdrop: Pond (from L100)", Gameplay, "Gameplay", "tall; short", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "procedural lawn tilted toward teal by the pond theme until `Backgrounds/gameplay-pond.png` exists (pictures.md B3)");
            Add("bg.theme.orchard", "Gameplay backdrop: Orchard (from L150)", Gameplay, "Gameplay", "tall; short", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "procedural lawn tilted warm by the orchard theme until `Backgrounds/gameplay-orchard.png` exists (pictures.md B4)");
            Add("bg.theme.moonlit_garden", "Gameplay backdrop: Moonlit Garden (from L200)", Gameplay, "Gameplay", "tall; short", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "procedural lawn, dusky and blue-green for the moonlit theme, until `Backgrounds/gameplay-moonlit.png` exists (pictures.md B5)");
            Add("bg.home", "Home scene: the garden behind the layered Home (sky, arches, flowers and paving, without the fountain: the owner's layer pack, spec 005 FR-028)", new[] { 1, 2, 3 }, "Home; splash", "early; progressed", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "procedural backdrop with arches until `Backgrounds/home.jpg` exists (pictures.md B1)");

            // Spec 005 FR-028: the owner's layered Home (HomeLayers, prepared by tools/heroanim/layers.mjs), drawn over
            // `bg.home` in its cover box, back to front, with the animated heroes between the layers.
            Add("bg.home.fountain_back", "Home layer: the lotus fountain's back (its basin, rim and lotus; Drop and Bloom stand in front of it)", new[] { 1, 2, 3 }, "Home; splash", "portrait", SizeClass.Screen, false, Launch, PlaceholderKind.Generated, "the owner's picture `Backgrounds/home-fountain-back.png` (tools/heroanim/layers.mjs); without it, or without the lotus or the front, Home shows the garden alone with no heroes");
            Add("bg.home.lotus", "Home layer: the lotus cut out of the fountain's back, drawn again over Bloom, who stands behind it", new[] { 1, 2, 3 }, "Home; splash", "portrait", SizeClass.Medium, false, Launch, PlaceholderKind.Generated, "the owner's picture `Backgrounds/home-lotus.png` (cut out of the fountain's back by tools/heroanim/layers.mjs); without it Home shows the garden alone with no heroes");
            Add("bg.home.fountain_front", "Home layer: the fountain's front stones and flowers, over the heroes' feet", new[] { 1, 2, 3 }, "Home; splash", "portrait", SizeClass.Screen, false, Launch, PlaceholderKind.Generated, "the owner's picture `Backgrounds/home-fountain-front.png` (tools/heroanim/layers.mjs); without it Home shows the garden alone with no heroes");
            Add("bg.home.shadow", "Home layer: the soft shadow under each hero's feet (one picture, as wide as the hero's seam pose)", new[] { 1, 2, 3 }, "Home; splash", "each hero", SizeClass.Medium, false, Launch, PlaceholderKind.Generated, "the owner's picture `Backgrounds/home-shadow.png` at 85% opacity (tools/heroanim/layers.mjs); without it the heroes stand without shadows");
            Add("bg.home.petals", "Home layer: the pink petals drifting down and swaying over the garden (drawn twice, a picture height apart, wrapping round)", new[] { 1, 2, 3 }, "Home; splash", "drifting", SizeClass.Screen, false, Launch, PlaceholderKind.Generated, "the owner's picture `Backgrounds/home-petals.png` at 90% opacity (tools/heroanim/layers.mjs); without it no petals drift over the layered Home (the drawn stand-in keeps its drawn petals `fx.petals`)");
            Add("bg.splash", "Splash backdrop", new[] { 1 }, "Splash", "portrait", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "the owner's Home garden (`Backgrounds/home.jpg`, `OwnerPictures.Resolve`; the procedural garden without it) until `Backgrounds/splash.png` exists (pictures.md B6)");
            Add("bg.wardrobe", "Wardrobe and Store backdrop: the garden arches behind the hero on its pedestal and behind the Store page (both builds)", new[] { 17 }, "Wardrobe; Store", "portrait", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "the warm Home garden backdrop (`HomeStage.Garden`) until `Backgrounds/wardrobe.png` exists (pictures.md B7)");
            Add("bg.win", "Win backdrop: the garden behind the full-screen celebration, calm in the middle with soft light from it (spec 005 FR-023)", new[] { 15, 16 }, "Win; milestone", "portrait", SizeClass.Screen, false, Launch, PlaceholderKind.Procedural, "the level's lawn (`BackdropScene.Win`) rendered at an eighth (blurred), lightened toward cream with a warm `ray.light` glow in the middle, until `Backgrounds/win.png` exists (pictures.md B8)");

            // ---- Characters ----
            Shape("char.sprig", "Sprig family body (the fallback figure when a picture is missing)", new[] { 2, 3, 7, 8, 9, 12, 13 }, "Pods; slots; walkers; Home; demos", "idle; walk; work; finish; stuck; celebrate", SizeClass.Medium, readability: true);
            Shape("char.bloom", "Bloom family body (the fallback figure when a picture is missing)", new[] { 2, 3, 7, 8, 9, 12, 13 }, "Pods; slots; walkers; Home; demos", "idle; walk; work; finish; stuck; celebrate", SizeClass.Medium, readability: true);
            Shape("char.drop", "Drop family body (the fallback figure when a picture is missing)", new[] { 2, 3, 7, 8, 9, 12, 13 }, "Pods; slots; walkers; Home; demos", "idle; walk; work; finish; stuck; celebrate", SizeClass.Medium, readability: true);
            Shape("char.twig", "Twig family body (the fallback figure when a picture is missing)", new[] { 2, 3, 7, 8, 9, 12, 13 }, "Pods; slots; walkers; Home; demos", "idle; walk; work; finish; stuck; celebrate", SizeClass.Medium, readability: true);
            Add("char.hero.home", "Home hero: a large Bloomling in the player's outfit", new[] { 3 }, "Home", "idle; reaction; each family; outfit layers", SizeClass.Large, false, Launch, PlaceholderKind.Generated, "over the owner's layered Home the family's animated hero (`char.hero3d.motion.{family}`) with worn cosmetics; on the drawn stand-in its 3D solo hero `3d/{family}`");

            // Spec 004: each variant is a 2D character whose whole shape is its symbol, and each family a 3D hero for the
            // meta screens. The pictures are generated by tools/artgen (contracts/art-files.md).
            foreach (VariantInfo variant in VariantCatalog.Default.All)
            {
                bool atLaunch = variant.Status == VariantStatus.Launch;
                Add(CharacterArt.Slot2D(variant.IconId), "Variant character: " + variant.Id.Key + " (its shape is the symbol)", new[] { 7, 8, 9, 12, 13 }, "Pods; slots; walkers; board tiles", "happy; asleep (queued); worried (stuck); blank (worn expression)", SizeClass.Small, true, atLaunch ? Launch : Later, PlaceholderKind.Generated, "`2d/" + variant.IconId + "-{mood}.png`");
            }

            foreach (Family family in CharacterArt.Families)
            {
                Add(CharacterArt.HeroSlot(family), "3D hero: " + family, new[] { 3, 5 }, "Home; Wardrobe; profile; leaderboard", "face; blank (worn expression)", SizeClass.Medium, false, Launch, PlaceholderKind.Generated, "`" + CharacterArt.Hero(family) + ".png`");
            }

            Add(CharacterArt.GroupSlot, "3D heroes: the four families side by side (the hosts stand them on a stone pedestal)", new[] { 15, 16 }, "Win; milestone", "warm garden light", SizeClass.Large, false, Launch, PlaceholderKind.Generated, "`" + CharacterArt.Group + ".png`");
            foreach (Family family in CharacterArt.Families)
            {
                Add(CharacterArt.CheerSlot(family), "3D hero celebrating: " + family + " (the owner's picture, spec 005 pictures.md A7)", new[] { 15, 16 }, "Win; milestone (the level's main family)", "arms up, eyes closed with joy", SizeClass.Large, false, Later, PlaceholderKind.Generated, "none while the animated hero's frames exist (`" + HeroMotion.Slot(family) + "` celebrates instead); without them `" + CharacterArt.Cheer(family) + ".png`, and the group picture `" + CharacterArt.Group + ".png` without both");
            }

            // Spec 005 FR-028: the owner's animated FBX heroes, pre-rendered offline by tools/heroanim into flat frames
            // (constitution VII: no 3D model, scene or camera in the game; flat pictures on meta screens only).
            foreach (Family family in CharacterArt.Families)
            {
                string name = CharacterArt.FamilyName(family);
                Add(HeroMotion.Slot(family), "3D hero in motion: " + family + " (the owner's animated hero as pre-rendered flat frames, " + HeroMotion.Fps + "/s; spec 005 FR-028)", new[] { 1, 2, 3, 15, 16 }, "Splash; Home (around the lotus fountain, a tap makes it react); win and milestone (the level's main family)", "idle loop (4 s, breathing and sway); reaction (2 s, from and back to the idle's first pose, cross-fading when tapped mid-loop); outfit layers", SizeClass.Large, false, Launch, PlaceholderKind.Generated, "`" + HeroMotion.Folder + "/" + name + "-idle-NN.png` and `" + name + "-react-NN.png` (tools/heroanim), decoded when first drawn; while they are missing, the still hero `" + CharacterArt.Hero(family) + ".png` (Home) or `" + CharacterArt.Cheer(family) + ".png` (win)");
            }

            // ---- Variant symbols ----
            string[] launch = { "leaf", "moss", "flower", "bud", "drop", "dew", "log", "acorn" };
            string[] names = { "Leaf", "Moss", "Flower", "Violet Bud", "Water", "Dew", "Wood", "Acorn" };
            for (int i = 0; i < launch.Length; i++)
            {
                Shape("symbol." + launch[i], "Variant symbol: " + names[i], new[] { 7, 8, 9, 12, 13 }, "Tiles; pods; slots; walkers; demos; jam sheet", "tile; pod; slot; small", SizeClass.Icon, readability: true);
            }

            string[] expansion = { "vine", "berry", "mist", "bark" };
            string[] expansionNames = { "Vine", "Berry", "Mist", "Bark" };
            for (int i = 0; i < expansion.Length; i++)
            {
                Shape("symbol." + expansion[i], "Variant symbol: " + expansionNames[i] + " (expansion)", new[] { 7, 8, 9 }, "Tiles; pods; slots; walkers", "tile; pod; slot; small", SizeClass.Icon, readability: true, priority: Later);
            }

            // ---- Board tiles and overlays ----
            Add("tile.base", "Board tile (a target cell's top layer)", Gameplay, "Board", "normal; mystery; clearing (shrinks and fades)", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "the candy tile `tile.candy` (board style) nearly filling its cell, parted from its neighbors by the dark board gap");
            Add("tile.layer_peek", "Layered tile: the next layer peeking", Gameplay, "Board", "2 layers; 3 layers", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "a small candy tile of the next layer in a cream ring with a dark rim, in the tile's top-right corner");
            Shape("tile.mystery", "Mystery tile and mystery pod mark (?)", new[] { 9, 12 }, "Board; pods; slots", "hidden; revealing", SizeClass.Small, readability: true);
            Shape("tile.stone", "Stone blocker: the rock glyph carved into a raised sandy stone block (`mat.stone`)", new[] { 7, 9 }, "Board", "whole; cracking", SizeClass.Small, readability: true);
            Shape("tile.key", "Key (gold, on a cream disc in the tile's top-left corner)", new[] { 9 }, "Board; flights to locks", "on tile; flying", SizeClass.Icon, readability: true);
            Add("tile.ground", "Open ground (a restored cell of a picture role)", Gameplay, "Board", "restored", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "pale flat cell of the finished picture (its variant color lightened), small radius, faint inner shadow");
            Add("tile.grass", "Grass cell: a board cell of the picture's background (no role), so the board reads as garden (spec 005 FR-020)", new[] { 7, 8, 9, 15 }, "Board; finished picture (win, Collection)", "open; background", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "UiRaster.Grass picture: a muted lawn square with a soft mottle, short blades, a faint top shadow and a deeper rim (four variants)");
            // Spec 005 §3.1, §3.6: the candy tiles (UiRaster.Tile) and the stone border around the board.
            Add("tile.candy", "Candy tile, board style: a nearly square satin tile in the variant color with a thin top bevel and its symbol as a bold gem (spec 005 FR-026: a thick dark outline, a fill in a shade of the tile, a white highlight); the owner's field icon (`tile.gem.*`) replaces the drawn gem", Gameplay, "Board; demos", "normal; pressed; dimmed; grey; mystery", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "UiRaster.Tile picture (board style, `ShapeLibrary.GemSymbol`); with the owner's icon the face alone (`UiRaster.TileFace`) under the picture");
            Add("tile.candy.sticker", "Candy tile, sticker style: a detailed symbol with a dark outline in its own tone; the owner's detailed icon (`tile.icon.*`) replaces the drawn symbol", new[] { 7, 10, 12, 13 }, "Pods; slots; jam sheet; Collection", "normal; dimmed (queued); grey (stuck); mystery", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "UiRaster.Tile picture (sticker style); with the owner's icon the face alone (`UiRaster.TileFace`) under the picture");

            // Spec 005 pictures.md G9–G24: the owner's variant icons over the candy tile's face (OwnerPictures.TileIcon).
            for (int i = 0; i < launch.Length; i++)
            {
                Add(OwnerPictures.IconSlot(launch[i]), "Variant icon, detailed: " + names[i] + " (the owner's picture `Icons/" + OwnerPictures.VariantIcon(launch[i]) + ".png`, spec 005 pictures.md G" + (9 + i) + ")", new[] { 7, 10, 12, 13 }, "Pods; slots; jam sheet; flights; demos; kit sheet", "normal; dimmed (queued, faded); grey (stuck, a grey copy); pressed", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "the drawn sticker symbol `symbol." + launch[i] + "` (UiRaster.Tile, sticker style) until the picture exists; it covers about 70% of the tile");
            }

            for (int i = 0; i < launch.Length; i++)
            {
                Add(OwnerPictures.GemSlot(launch[i]), "Variant icon, simplified for the board: " + names[i] + " (the owner's picture `Icons/" + OwnerPictures.FieldIcon(launch[i]) + ".png`, spec 005 pictures.md G" + (17 + i) + ")", new[] { 7, 8, 9, 15 }, "Board tiles; layer peeks; specials; finished picture (win, Collection)", "normal; flat (finished picture)", SizeClass.Icon, true, Launch, PlaceholderKind.Procedural, "the drawn gem (`ShapeLibrary.GemSymbol`, UiRaster.Tile, board style) until the picture exists; it covers about 62% of the tile");
            }

            Add("board.border.stone", "Stone border around the board", Gameplay, "Board; win picture", "normal; thin (win)", SizeClass.Large, true, Launch, PlaceholderKind.Procedural, "UiRaster.Stone blocks (warm sandy stone) with dark joints, and dark lines between the tiles");
            Add("tile.picture", "Finished picture reveal", new[] { 6, 15 }, "Win; Collection", "reveal; framed", SizeClass.Large, true, Launch, PlaceholderKind.Procedural, "the level's cells as flat full-color candy tiles (`tile.candy`, no lip, with the owner's field icons `tile.gem.*`) of each role's variant in a thin stone border (spec 005 D14)");

            // ---- Specials ----
            Shape("special.gate", "Garden Gate (hedge seal)", new[] { 9 }, "Board", "closed; opening", SizeClass.Small, readability: true);
            Shape("special.fountain", "Fountain (also the bottom menu's Home stand-in)", new[] { 9 }, "Board; bottom menu (while `Icons/nav-home.png` is missing)", "dry; flowing", SizeClass.Small, readability: true);
            Shape("special.chest", "Sealed Chest", new[] { 9 }, "Board", "sealed; open", SizeClass.Small, readability: true);
            Shape("special.statue", "Statue", new[] { 9 }, "Board", "waiting; restored", SizeClass.Small, readability: true);
            Shape("special.bridge", "Bridge (repaired)", new[] { 9 }, "Board", "repaired", SizeClass.Small, readability: true);
            Shape("special.bridge_broken", "Bridge (broken)", new[] { 9 }, "Board", "broken", SizeClass.Small, readability: true);
            Shape("special.region", "Region marker (restore this whole area)", new[] { 9 }, "Board", "pending; done", SizeClass.Small, readability: true);

            // ---- Pods and slots ----
            Add("pod.card", "Spirit Pod (spec 005 §3.7)", new[] { 7, 8, 9, 12 }, "Tray", "exposed (bright, takes the tap); waiting in its column (muted); pressed (sunk)", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "a dark wooden frame 1.3 times as wide as tall (`mat.wood.dark`) around a cream panel tinted by the variant, the owner's icon of the variant (`tile.icon.*`) alone over its middle and the small outlined count at its bottom right corner (the owner's choice E, 2026-10-03); the sticker tile (`tile.candy.sticker`) stands in without the picture; a waiting pod shows the same parts muted (a lighter wash, a veiled frame, the icon at 0.7, a softer count)");
            Add("pod.state.locked", "Locked pod", new[] { 12 }, "Tray", "locked; unlocking", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "the wooden frame around a grey panel with a padlock and the softer count");
            Add("pod.state.mystery", "Mystery pod", new[] { 12 }, "Tray; slots", "hidden; revealing", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "the lilac mystery tile with a white ? (`tile.mystery`) and its count; it flips over to the variant tile in its slot");
            Add("pod.link", "Connected pods link", new[] { 12 }, "Tray", "pair; triple", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "a teal bar with a white rim and a light streak, riveted to each wooden frame; a ring of the group's color on a frame's top right corner when the members lie on different rows");
            Add("pod.deck", "Source stack column (spec 005 FR-021; the owner's rule of 2026-10-03)", new[] { 7, 8, 9, 12 }, "Tray", "next pods (two on 16:9, three from 19.5:9); more below (+N); sliding up or down a row; emptied stack", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "the stack's pods one after another in a column, never on each other: the exposed pod in the top row and the next ones in the rows under it, each fully visible (`pod.card`, waiting look; a hidden mystery pod shows its ? and count, a locked one its padlock); the +N count badge on the last shown pod's top left corner; the pods slide up a row when the exposed one leaves and down when Return puts one back; a sunk parchment well for an emptied stack");
            Add("pod.count", "Pod and slot count", new[] { 7, 12, 13 }, "Pods; slots; jam row", "normal; dropping; dimmed", SizeClass.Icon, true, Launch, PlaceholderKind.Procedural, "small brown digits in a white outline, no \"x\": at a pod's bottom right corner over its icon; plain below a slot's tile");
            Add("slot.empty", "Empty Waiting Slot", new[] { 7, 13 }, "Slots", "empty", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "a cream plate pressed into the parchment with a light inner ring and a stitched dashed inner outline");
            Add("slot.state.working", "Working pod in a slot", new[] { 13 }, "Slots", "working; finishing", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "a raised cream plate with the variant's sticker tile and the plain count below it");
            Add("slot.state.stuck", "Stuck (waiting) pod in a slot", new[] { 13 }, "Slots", "stuck", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "the raised cream plate with the tile in grey, a softer count and the hourglass badge");
            Shape("slot.state.waiting", "Waiting mark (hourglass)", new[] { 13 }, "Slots", "waiting", SizeClass.Icon, readability: true);
            Shape("slot.state.jam_risk", "Jam-risk mark (!)", new[] { 13 }, "Slots", "risk", SizeClass.Icon, readability: true);
            Add("slot.state.locked", "Locked slot", new[] { 13 }, "Slots", "locked; opening", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "a grey raised plate with a padlock");
            Shape("slot.state.danger", "Danger slot frame (the last free usable slot)", new[] { 13 }, "Slots", "danger (4/5 used)", SizeClass.Small, readability: true);
            Add("slot.extra", "Extra slot (from the Extra Slot booster)", new[] { 13 }, "Slots", "added", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "a plate with a green \"+\" badge over its upper left corner");
            Add("slot.state.target", "Return target (a pod Return can take back)", new[] { 13 }, "Slots", "targeting", SizeClass.Small, true, Launch, PlaceholderKind.Procedural, "the selected booster's pulsing golden glow and ring around the plate");

            // ---- Boosters ----
            Shape("booster.extra_slot", "Booster: Extra Slot (the owner's picture `Icons/booster-extra_slot.png` replaces the drawn icon, spec 005 pictures.md D1)", new[] { 7, 8, 9, 10, 14, 16, 17 }, "Booster bar; jam sheet; Store; rewards; demos", "available; count; price; disabled", SizeClass.Small);
            Shape("booster.shuffle", "Booster: Shuffle (the owner's picture `Icons/booster-shuffle.png` replaces the drawn icon, pictures.md D2)", new[] { 7, 8, 9, 10, 14, 16, 17 }, "Booster bar; jam sheet; Store; rewards; demos", "available; count; price; disabled", SizeClass.Small);
            Shape("booster.return", "Booster: Return (the owner's picture `Icons/booster-return.png` replaces the drawn icon, pictures.md D3)", new[] { 7, 8, 9, 10, 14, 17 }, "Booster bar; jam sheet; Store; demos", "available; count; price; disabled; targeting", SizeClass.Small);
            Shape("booster.bloom_burst", "Booster: Bloom Burst (the owner's picture `Icons/booster-bloom_burst.png` replaces the drawn icon, pictures.md D4)", new[] { 9, 14, 17 }, "Booster bar; jam sheet; Store; demos", "available; count; price; disabled; targeting", SizeClass.Small);
            // Spec 005 §3.8: the colored icons are drawn from parts (GardenLook.BoosterIcon); the ids above are their one-color silhouettes.
            Shape("booster.extra_slot.disc", "Booster icon part: Extra Slot's blue disc", new[] { 10, 14, 17 }, "Booster tiles; jam choices; Store", "colored icon");
            Shape("booster.extra_slot.plus", "Booster icon part: Extra Slot's white plus", new[] { 10, 14, 17 }, "Booster tiles; jam choices; Store", "colored icon");
            Shape("booster.shuffle.a", "Booster icon part: Shuffle's orange arrow", new[] { 10, 14, 17 }, "Booster tiles; jam choices; Store", "colored icon");
            Shape("booster.shuffle.b", "Booster icon part: Shuffle's green arrow", new[] { 10, 14, 17 }, "Booster tiles; jam choices; Store", "colored icon");
            Shape("booster.bloom_burst.petals", "Booster icon part: Bloom Burst's pink petals", new[] { 10, 14, 17 }, "Booster tiles; jam choices; Store", "colored icon");
            Shape("booster.bloom_burst.center", "Booster icon part: Bloom Burst's yellow center", new[] { 10, 14, 17 }, "Booster tiles; jam choices; Store", "colored icon");
            Add("booster.tile", "Booster tile (spec 005 §3.7)", new[] { 7, 8, 9, 14 }, "Booster bar", "charges; price; selected; disabled; pressed", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "a cream squircle face set in a silver-grey bezel with a deeper grey lip, a light edge and a soft shadow; the count badge over its lower right corner or the cost pill below it");

            // ---- UI kit ----
            Shape("ui.panel", "Rounded panel base (9-slice)", new[] { 4, 5, 6, 10, 11, 15, 16, 17 }, "Every card, button, pill and tile", "any tint", SizeClass.Small);
            Shape("ui.circle", "Disc (round buttons, badges, avatars)", new[] { 2, 3, 5, 7, 14 }, "Round buttons; badges; medals; avatars", "any tint", SizeClass.Icon);
            Shape("ui.ring", "Ring (highlights, profile frame)", new[] { 3, 7 }, "Highlights; entry marker; avatar frame", "any tint", SizeClass.Icon);
            Add("ui.button.primary", "Primary button (green, darker lower edge)", new[] { 2, 3, 4, 10, 11, 15, 16 }, "PLAY; NEXT; CLAIM; RESUME; CONTINUE; Free rescue", "normal; pressed; disabled", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "glossy green raised pill in a light wood rim (`ui.button.rim`): outline, lip, highlight band, volumetric label");
            Add("ui.button.secondary", "Secondary button (cream)", new[] { 4, 10, 11, 15 }, "RESTART; SETTINGS; HOME; Restart; ×2 reward; Get +N", "normal; pressed; disabled", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "cream raised pill on a cream plate, cream outline, brown label and glyph");
            Add("ui.button.round", "Round or squircle icon button (cream)", new[] { 2, 3, 7, 11 }, "Settings; Pause; close; back; Daily Challenge", "normal; pressed; circle; squircle", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "one domed cream cushion (peach edges, lighter middle) with a lip, a soft tan outline, a soft shadow and a brown glyph in a thin cream halo");
            Add("ui.pill.level", "Level label of the gameplay top bar", Gameplay, "Gameplay top bar", "normal; super hard", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "a wooden sign with ivy (`ui.sign.wood`, `ui.sign.ivy`) and brown \"Level N\"; purple letters on Super Hard");
            Add("ui.pill.speed", "2× speed pill", Gameplay, "Gameplay top bar", "1×; 2×", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "cream squircle pill with the brown speed and the `ui.fast` chevrons");
            Add("ui.pill.petals", "Petals balance pill", new[] { 2, 3, 17 }, "Home; Store", "with +; without +", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "cream raised pill fitting its amount: the lotus inside its left end, the brown balance right after it and a round green + over its right end (`PetalsPillParts`)");
            Add("ui.badge.hard", "HARD badge", new[] { 8 }, "Gameplay", "intro; steady", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "red raised sticker pill on a plate");
            Add("ui.badge.super_hard", "SUPER HARD badge", new[] { 9 }, "Gameplay", "intro; steady", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "purple raised sticker pill on a plate");
            Add("ui.badge.count", "Count badge (booster charges, +N on a stack)", new[] { 7, 12, 14 }, "Booster bar; tray", "count", SizeClass.Icon, false, Launch, PlaceholderKind.Procedural, "dark green disc with a white ring and white digits");
            Add("ui.card", "Popup card frame", new[] { 4, 5, 6, 11, 16 }, "Daily Reward; Leaderboard; Collection; Pause; Milestone; Settings; Wardrobe", "with close; without close", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "parchment card (`mat.parchment`) with a brown title or a wooden sign header and a cream round close, over a scrim");
            Add("ui.sheet", "Jam card frame (spec 005 FR-022)", new[] { 10 }, "Jam", "popping in; open", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "a parchment card in the middle of the screen over the warm scrim, with a brown title and a soft brown subtitle (two lines when long), popping in");
            Add("ui.row", "List row (Store, Leaderboard)", new[] { 5, 17 }, "Store; Leaderboard", "normal; highlighted (You); unavailable", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "cream rounded panel with a cream outline; the own row raised and green-tinted");
            Add("ui.tab", "Tab", new[] { 17 }, "Store; Wardrobe", "selected; unselected", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "selected: glossy green raised pill on a plate; others: parchment wells");
            Add("ui.toggle", "Toggle switch", Array.Empty<int>(), "Settings", "on; off", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "a track pressed into the parchment (on: the glossy green face with a white check; off: a parchment well) and a domed cream knob");
            // Spec 005 §3.2 to §3.6: wooden signs and rims, jam choices, cost pills, the stone pedestal, the wooden wordmark.
            Add("ui.sign.wood", "Wooden sign (level label, win and banner titles, Home level plaque)", new[] { 2, 3, 7, 15, 17 }, "Gameplay top bar; win; Home; Store; Wardrobe", "plain; ivy; flowers; super hard letters", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "UiRaster.Plank (light wood) with brown embossed letters and a soft shadow");
            Shape("ui.sign.ivy", "Ivy cluster over a sign's ends (clovers with pointed leaflets, at the top and bottom corners; the owner's picture `Decor/ivy.png`, mirrored for the right end, replaces it, pictures.md D5)", new[] { 7, 17 }, "Gameplay level sign; Store and Wardrobe banners; wordmark", "left; right (mirrored)", SizeClass.Small);
            Add("ui.sign.flowers", "Flower clusters on the win and milestone signs (the owner's picture `Decor/flowers.png`, mirrored for the other end, replaces them, pictures.md D6)", new[] { 15, 16 }, "Win sign; milestone sign", "top-left; other end (mirrored)", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "lush clusters of five big leaves with veins and two white flowers at two corners (`ui.deco.garden`)");
            Add("ui.button.rim", "Light wood rim of the main buttons", new[] { 2, 3, 10, 11, 15, 16 }, "PLAY; NEXT; RESUME; CLAIM; CONTINUE; Free rescue", "normal; pressed", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "UiRaster.Plank (pale wood, only a thin deeper bottom band) behind the green face");
            Add("ui.button.choice", "Jam choice button (icon above the label, cost pill below)", new[] { 10 }, "Jam sheet", "green; blue; pressed; disabled", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "glossy green or blue rounded rectangle with the booster icon, a white outlined label and a cost pill");
            Add("ui.pill.cost", "Cost pill (lotus and price, Free, ×N)", new[] { 10, 14, 17 }, "Jam choices; booster tiles; Store", "price; free; charges", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "cream pill with a cream outline: the lotus and a brown price, a green ▶ square and Free, or ×N");
            Add("ui.pedestal", "Stone pedestal under the heroes", new[] { 2, 3, 15, 16 }, "Win; milestone; Home; Wardrobe", "normal", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "UiRaster.Pedestal picture: a warm grey-beige ellipse-topped stone drum with block joints, a crack, moss tufts and a dark outline (the win stands on the owner's painted disc instead when `Backgrounds/win.jpg` exists)");
            Add("ui.logo.wood", "Wooden wordmark letters (the stand-in for the owner's logo; its leaves are the owner's `Decor/logo-leaves.png` when it exists, pictures.md D8)", new[] { 1, 2, 3 }, "Splash; Home", "full; compact", SizeClass.Large, false, Launch, PlaceholderKind.Text, "wordmark text in pale cream-yellow wood with a wood outline and extrusion, ivy clusters and a pink flower");
            // Spec 005 §4.5, §4.6: the Wardrobe look of the meta screens (the playtest's Store cosmetics) and the drawn Home stage.
            Add("ui.tab.family", "Family tab (Wardrobe; the Store's cosmetics)", new[] { 17 }, "Store cosmetics; Wardrobe", "selected (lighter, joined to the panel); unselected", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "cream tab with rounded top corners holding the family's 3D hero and its name; the selected one lighter and flowing into the panel below");
            Add("ui.card.outfit", "Outfit card (Wardrobe; the Store's cosmetics)", new[] { 17 }, "Store cosmetics; Wardrobe", "normal; worn; for sale (cost pill); locked (padlock)", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "cream card with a beige picture well showing the hero in the item and the name below; the worn one green-tinted with a green border and a check badge; a locked one faded with a padlock badge");
            Add("ui.fountain", "Lotus fountain of the drawn Home stage (the stand-in for the owner's Home diorama)", new[] { 1, 2 }, "Splash; Home (early)", "normal", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "a small stone basin (`ui.pedestal`) with water, two lily pads and the pink lotus, between the heroes on the stone pedestal");
            Shape("ui.close", "Close glyph", new[] { 4, 5, 6, 11 }, "Cards", "normal");
            Shape("ui.pause", "Pause glyph", Gameplay, "Gameplay top bar", "normal");
            Shape("ui.restart", "Restart glyph", new[] { 10, 11 }, "Pause card; jam sheet", "normal");
            Shape("ui.settings", "Settings glyph (gear)", new[] { 2, 3, 11 }, "Home; Pause card", "normal");
            Shape("ui.chevron", "Chevron (opens a screen, turns a page)", new[] { 17 }, "Daily Challenge card; ‹ › arrows", "normal");
            Shape("ui.plus", "Plus glyph", new[] { 2, 3, 17 }, "Petals pill; + Slot", "normal");
            Shape("ui.check", "Check mark (done)", new[] { 3 }, "Home Daily Challenge card (done today)", "normal");
            Shape("ui.play", "Play triangle, as tall as the letters (spec 003 FR-010)", new[] { 2, 3 }, "PLAY on Home", "normal; pressed");
            Shape("ui.fast", "Fast glyph (two chevrons) of the speed pill (spec 005)", Gameplay, "Gameplay top bar", "normal");
            Shape("ui.back", "Back arrow glyph (spec 005)", new[] { 17 }, "Wardrobe; Store", "normal");
            Shape("ui.deco.garden", "Leaves and a white flower on the main buttons (spec 003 FR-011a; the owner's picture `Decor/button-leaves.png`, turned half way for the bottom right, replaces them, pictures.md D7)", new[] { 2, 3, 11, 15, 16 }, "PLAY; RESUME; NEXT; CONTINUE; CLAIM", "top-left; bottom-right (turned)", SizeClass.Small);
            Shape("ui.gift", "Gift (milestone teaser)", new[] { 3 }, "Home", "normal; ready", SizeClass.Small);
            Shape("ui.trophy", "Trophy (Get +N; the bottom menu's Leaderboard stand-in)", new[] { 4 }, "Daily Reward; bottom menu (while `Icons/nav-leaderboard.png` is missing)", "normal", SizeClass.Small);
            Shape("ui.medal", "Medal (ranks 1–3)", new[] { 5 }, "Leaderboard", "gold; silver; bronze", SizeClass.Small);
            Shape("ui.ad", "Rewarded-ad mark (video)", new[] { 4, 10, 15 }, "Get +N; Free rescue; ×2 reward; free booster", "normal");
            Shape("ui.shirt", "Wardrobe glyph (the bottom menu's stand-in)", new[] { 3 }, "Bottom menu (while `Icons/nav-wardrobe.png` is missing)", "normal");
            Shape("ui.grid", "Collection glyph (the bottom menu's stand-in)", new[] { 3 }, "Bottom menu (while `Icons/nav-collection.png` is missing)", "normal");
            Shape("ui.sun", "Daily Challenge glyph", new[] { 3 }, "Home Daily Challenge card", "normal; done", SizeClass.Small);
            Shape("ui.person", "Player avatar placeholder", new[] { 5 }, "Leaderboard; profile", "any tint", SizeClass.Small);
            Shape("ui.lock", "Padlock", new[] { 9, 12, 13, 14 }, "Locked pods, slots and cells; locked boosters", "closed; opening", readability: true);
            Shape("ui.star", "Star (Hard label, badge)", new[] { 8 }, "Difficulty intro; badges", "normal");
            Shape("ui.star2", "Double star (Super Hard label, marker)", new[] { 9 }, "Difficulty intro; markers", "normal");
            Shape("ui.cross", "Ignore mark (a pod ignores another variant)", Array.Empty<int>(), "Variant demo (spec 001 FR-071)", "normal");
            Shape("ui.pointer", "Tutorial pointing hand", Array.Empty<int>(), "Demos", "tap; hold", SizeClass.Small);
            // Spec 005 §4.3 and §4.4: the jam's slot row and the reward pills of the win and the milestone.
            Add("ui.jam.slots", "Jam sheet: the inset row of the Waiting Slots' contents", new[] { 10 }, "Jam sheet", "jammed (all full); stuck (free and locked slots too)", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "a sunk parchment well with each slot's sticker tile (`tile.candy.sticker`) and its brown count; free slots as small dashed plates, locked ones with the padlock");
            Add("ui.pill.reward", "Reward pill (win, milestone)", new[] { 15, 16 }, "Win; milestone", "counting up; steady", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "the cream cost pill (`ui.pill.cost`), bigger, with the lotus and \"+N\" counting up; on the milestone each reward on a cream tile with its amount in the pill");

            // Spec 005 FR-030 (the owner's bottom menu, the wooden variant, 2026-10-04): the bar, its medallion and the
            // owner's five icons (OwnerPictures.NavIcon), on Home, the Store page and the Wardrobe.
            Add("ui.nav.bar", "Bottom menu: the wooden bar across the screen's bottom (spec 005 FR-030)", new[] { 2, 3, 17 }, "Home; Store page; Wardrobe", "one to five places; grooves between them", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "UiRaster.NavBar picture: a warm brown plank (`wood.dark_top` to `wood.dark`, grained, rounded ends) from 0.12 W above the safe bottom to the screen's bottom, thin carved grooves between the places, and green vines with leaves and white flowers curling around both ends");
            Add("ui.nav.medallion", "Bottom menu: the raised round medallion of the active place", new[] { 2, 3, 17 }, "Home; Store page; Wardrobe", "Home; Shop; Wardrobe", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "UiRaster.NavMedallion picture: a lighter honey wood disc in a darker wooden rim, rising 0.05 W above the plank, with short vines, eight leaves and two small white flowers on its rim and a soft shadow under it");
            foreach (NavPlace place in BottomNav.Order)
            {
                string glyph = BottomNav.Fallback(place).ShapeId;
                Add(BottomNav.Slot(place), "Bottom menu icon: " + place + " (the owner's picture `Icons/" + OwnerPictures.NavIcon(place) + ".png`, spec 005 pictures.md D" + (9 + IndexOf(BottomNav.Order, place)) + ")", new[] { 2, 3, 17 }, "Bottom menu (on the plank; in the medallion when active)", "on the plank; in the medallion; pressed", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "the `" + glyph + "` glyph in its color over a darker outline until the picture exists");
            }

            // ---- Materials (spec 005 FR-006, contracts/look.md §2) ----
            Add("mat.wood.light", "Light wood (signs, button rims)", new[] { 2, 3, 7, 15 }, "Signs; main button rims; wordmark", "any size; grain by seed", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "UiRaster.Plank, light tone");
            Add("mat.wood.dark", "Dark wood (pod frames)", new[] { 7, 12 }, "Pods", "exposed; waiting (veiled); locked", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "UiRaster.Frame, dark tone");
            Add("mat.stone", "Stone blocks (board border, pedestal)", new[] { 7, 15 }, "Board border; pedestal", "any size; moss by seed", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "UiRaster.Stone and Pedestal (warm sandy stone, smooth, a few soft moss tufts)");
            Add("mat.parchment", "Parchment (cards, sheet, tray, slot band)", new[] { 4, 5, 6, 10, 11, 17 }, "Cards; jam sheet; tray; slot band; toasts", "any size", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "parchment gradient with a warm aged edge band, a thin brown outline and a thin inner line");

            // ---- Currency and rewards ----
            Shape("currency.petal", "Petals symbol (soft currency): a pink lotus (spec 005; the owner's picture `Icons/" + OwnerPictures.CurrencyLotus + ".png` replaces the drawn lotus)", new[] { 2, 3, 4, 10, 15, 16, 17 }, "Petals pill; rewards; costs; prices; badges", "small; large", SizeClass.Icon);
            Shape("currency.petal.front", "Lotus part: the front petals (center and sides) and the base", new[] { 2, 3, 4, 10, 15, 16, 17 }, "Wherever the lotus shows", "small; large", SizeClass.Icon);
            Shape("currency.petal.tips", "Lotus part: the near-white petal middles", new[] { 2, 3, 4, 10, 15, 16, 17 }, "Wherever the lotus shows", "small; large", SizeClass.Icon);
            Shape("currency.reward_basket", "Reward basket (Daily Reward; the bottom menu's Shop stand-in)", new[] { 4 }, "Daily Reward; bottom menu (while `Icons/nav-shop.png` is missing)", "day 1–7", SizeClass.Medium);
            Add("currency.petal_pile", "Pile of Petals (big rewards)", new[] { 4, 16 }, "Daily Reward; Milestone", "small; large", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "a cluster of Petal symbols");

            // ---- Collection ----
            Add("collection.frame", "Collection picture frame", new[] { 6 }, "Collection grid", "normal; new", SizeClass.Small, false, Launch, PlaceholderKind.Procedural, "cream rounded frame with a soft edge");
            Add("collection.detail_frame", "Collection detail frame", new[] { 6 }, "Collection detail", "normal", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "large rounded frame with the name and level");

            // ---- Cosmetics ----
            Shape("cosmetic.sprout", "Hat: Sprout", new[] { 16 }, "Wardrobe; walkers; Home hero; milestone rewards", "worn; preview");
            Shape("cosmetic.cap", "Hat: Cap", new[] { 16 }, "Wardrobe; walkers; Home hero; milestone rewards", "worn; preview");
            Shape("cosmetic.brim", "Hat: Brim hat", new[] { 16 }, "Wardrobe; walkers; Home hero; milestone rewards", "worn; preview");
            Shape("cosmetic.crown", "Hat: Crown", Array.Empty<int>(), "Wardrobe; walkers; Home hero", "worn; preview", priority: Later);
            Shape("cosmetic.nightcap", "Hat: Nightcap", Array.Empty<int>(), "Wardrobe; walkers; Home hero", "worn; preview", priority: Later);
            Shape("cosmetic.sparkle", "Trail: Sparkle", Array.Empty<int>(), "Wardrobe; walkers", "worn; preview", priority: Later);
            Shape("cosmetic.swirl", "Trail: Swirl", Array.Empty<int>(), "Wardrobe; walkers", "worn; preview", priority: Later);
            Shape("cosmetic.wink", "Expression: Wink", Array.Empty<int>(), "Wardrobe; walkers", "worn; preview", priority: Later);
            Shape("cosmetic.smile", "Expression: Smile", Array.Empty<int>(), "Wardrobe; walkers", "worn; preview", priority: Later);
            Shape("cosmetic.stars", "Expression: Star eyes", Array.Empty<int>(), "Wardrobe; walkers", "worn; preview", priority: Later);
            Shape("cosmetic.sleepy", "Expression: Sleepy", Array.Empty<int>(), "Wardrobe; walkers; stuck pods", "worn; preview");
            Shape("cosmetic.spots", "Skin: Spots", Array.Empty<int>(), "Wardrobe; pods; walkers", "on each family", priority: Later);
            Shape("cosmetic.stripes", "Skin: Stripes", Array.Empty<int>(), "Wardrobe; pods; walkers", "on each family", priority: Later);
            Shape("cosmetic.petals", "Skin: Petals", Array.Empty<int>(), "Wardrobe; pods; walkers", "on each family", priority: Later);
            Shape("cosmetic.speckles", "Skin: Speckles", Array.Empty<int>(), "Wardrobe; pods; walkers", "on each family", priority: Later);
            Shape("cosmetic.frame", "Profile frame", new[] { 5 }, "Own leaderboard row; Wardrobe (the profile avatar)", "each frame item", SizeClass.Small);
            Shape("cosmetic.badge", "Profile badge (incl. level badges)", new[] { 5 }, "Wardrobe (the profile avatar)", "each badge item; level N", SizeClass.Small);
            Shape("cosmetic.marker", "Leaderboard marker (incl. level markers)", new[] { 5 }, "Own leaderboard row; Wardrobe", "each marker item; level N", SizeClass.Small);

            // ---- Effects ----
            Shape("fx.sparkle", "Sparkle", new[] { 7, 15 }, "Clears; win shine; burst", "small; large", SizeClass.Icon);
            Shape("fx.petal_burst", "Petal burst", new[] { 15, 16 }, "Win; milestone; rewards", "burst", SizeClass.Icon);
            Shape("fx.droplet", "Droplets (Drop-family clears)", new[] { 7, 8, 9 }, "Board: tiles restored by Drop Bloomlings", "splash", SizeClass.Icon);
            Add("fx.rays", "Light rays behind the celebrating heroes", new[] { 15, 16 }, "Win; milestone", "slowly turning", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "ten soft ray-light wedges from the pedestal");
            Shape("fx.petals", "Falling petals of the win", new[] { 15, 16 }, "Win; milestone", "drifting; swaying", SizeClass.Icon);
            Add("fx.confetti", "Confetti", new[] { 15, 16 }, "Win; milestone", "fall", SizeClass.Icon, false, Launch, PlaceholderKind.Procedural, "small rotating squares in level colors");
            Add("fx.puff", "Puff (a pod leaves its slot)", new[] { 13 }, "Slots", "puff", SizeClass.Icon, false, Launch, PlaceholderKind.Procedural, "expanding fading discs");
            Add("fx.shuffle_swirl", "Shuffle swirl", new[] { 14 }, "Tray", "swirl", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "pods spinning in place");
            Add("fx.burst", "Bloom Burst blast", new[] { 9, 14 }, "Board", "blast", SizeClass.Medium, false, Launch, PlaceholderKind.Procedural, "pulsing targets and sparkles");
            Add("fx.win_shine", "Finished picture shine", new[] { 15 }, "Win", "sweep", SizeClass.Large, false, Launch, PlaceholderKind.Procedural, "a light band sweeping the picture");

            // ---- Typography ----
            Add("font.display", "Display font (rounded, bold): titles, buttons, pills, wordmark", new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 14, 15, 16, 17 }, "Every screen", "bold; outlined; volumetric on colored faces", SizeClass.Icon, true, Launch, PlaceholderKind.BundledFont, "Nunito ExtraBold (SIL OFL 1.1), `UI/Fonts/Resources/Nunito-ExtraBold.ttf`");
            Add("font.body", "Body font: rows, captions, numbers", new[] { 3, 4, 5, 6, 10, 17 }, "Every screen", "regular; bold digits", SizeClass.Icon, true, Launch, PlaceholderKind.BundledFont, "Nunito SemiBold (SIL OFL 1.1), `UI/Fonts/Resources/Nunito-SemiBold.ttf`");

            // ---- Audio ----
            Add("audio.music.daylight_garden", "Music: Daylight Garden", Gameplay, "Gameplay; Home", "loop", SizeClass.Audio, false, Launch, PlaceholderKind.Synth, "none (silence); cues only");
            Add("audio.music.pond", "Music: Pond", Gameplay, "Gameplay", "loop", SizeClass.Audio, false, Later, PlaceholderKind.Synth, "none (silence); cues only");
            Add("audio.music.orchard", "Music: Orchard", Gameplay, "Gameplay", "loop", SizeClass.Audio, false, Later, PlaceholderKind.Synth, "none (silence); cues only");
            Add("audio.music.moonlit_garden", "Music: Moonlit Garden", Gameplay, "Gameplay", "loop", SizeClass.Audio, false, Later, PlaceholderKind.Synth, "none (silence); cues only");
            foreach ((string cue, string title, string use) in Cues)
            {
                Add("audio.cue." + cue, "Sound: " + title, Array.Empty<int>(), use, "one-shot", SizeClass.Audio, false, Launch, PlaceholderKind.Synth, "synthesized tone");
            }

            return list;
        }

        private static int IndexOf(IReadOnlyList<NavPlace> places, NavPlace place)
        {
            for (int i = 0; i < places.Count; i++)
            {
                if (places[i] == place)
                {
                    return i;
                }
            }

            return -1;
        }

        private static IReadOnlyList<string> Split(string text) =>
            text.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries).Select(s => s.Trim()).Where(s => s.Length > 0).ToArray();
    }
}
