// <auto-generated>
// Written by tools/heroanim/layers.mjs from the owner's Home layers; do not edit. `node tools/heroanim/check.mjs` proves
// it still matches the pictures.
// </auto-generated>
namespace Bloomlings.Client.UI.Design
{
    public static partial class HomeLayers
    {
        /// <summary>The layered picture's width in pixels (every layer's box is in its pixels).</summary>
        public const int PictureWidth = 852;

        /// <summary>The layered picture's height in pixels.</summary>
        public const int PictureHeight = 1846;

        /// <summary><c>home.jpg</c> (from <c>01_home_bg_back.png</c>): its box in the picture.</summary>
        public static readonly PictureBox Back = new PictureBox("home", 0, 0, 852, 1846);

        /// <summary><c>home-fountain-back.png</c> (from <c>02_home_fountain_back.png</c>): its box in the picture.</summary>
        public static readonly PictureBox FountainBack = new PictureBox("home-fountain-back", 0, 700, 852, 540);

        /// <summary><c>home-fountain-front.png</c> (from <c>03_home_fountain_front.png</c>): its box in the picture.</summary>
        public static readonly PictureBox FountainFront = new PictureBox("home-fountain-front", 0, 987, 852, 342);

        /// <summary><c>home-lotus.png</c> (from <c>02_home_fountain_back.png (the lotus)</c>): its box in the picture.</summary>
        public static readonly PictureBox Lotus = new PictureBox("home-lotus", 294, 835, 269, 159);

        /// <summary><c>home-shadow.png</c> (from <c>04_home_soft_shadow.png (the front left shadow)</c>): its box in the picture.</summary>
        public static readonly PictureBox Shadow = new PictureBox("home-shadow", 0, 918, 410, 175);
    }
}
