// <auto-generated>
// Written by tools/heroanim/layers.mjs from the owner's Home layers; since 2026-10-08 the boxes of the owner's restyled
// cut-outs, placed by hand (tools/heroanim/SOURCE.md). `node tools/heroanim/check.mjs` proves it still matches the pictures.
// </auto-generated>
namespace Bloomlings.Client.UI.Design
{
    public static partial class HomeLayers
    {
        /// <summary>The layered picture's width in pixels (every layer's box is in its pixels).</summary>
        public const int PictureWidth = 852;

        /// <summary>The layered picture's height in pixels.</summary>
        public const int PictureHeight = 1846;

        /// <summary><c>home.jpg</c> (the owner's new garden, 2026-10-08): its box in the picture.</summary>
        public static readonly PictureBox Back = new PictureBox("home", 0, 0, 852, 1846);

        /// <summary><c>home-fountain-back.png</c> (the owner's restyled fountain back, 2026-10-08): its box in the picture.</summary>
        public static readonly PictureBox FountainBack = new PictureBox("home-fountain-back", 0, 736, 852, 504);

        /// <summary><c>home-fountain-front.png</c> (the owner's restyled front stones, 2026-10-08): its box in the picture.</summary>
        public static readonly PictureBox FountainFront = new PictureBox("home-fountain-front", 0, 990, 852, 261);

        /// <summary><c>home-lotus.png</c> (the owner's restyled lotus, 2026-10-08): its box in the picture.</summary>
        public static readonly PictureBox Lotus = new PictureBox("home-lotus", 294, 835, 269, 159);

        /// <summary><c>home-shadow.png</c> (the owner's restyled shadow, 2026-10-08): its box in the picture.</summary>
        public static readonly PictureBox Shadow = new PictureBox("home-shadow", 0, 918, 410, 72);
    }
}
