// Pre-renders the owner's animated FBX heroes (models/*.fbx) into flat frame pictures (spec 005 FR-028, constitution VII:
// pre-rendered 3D shows on meta screens as flat pictures only). For every hero of heroes.json it renders the idle loop
// and the reaction (and a win's celebration when the hero has one) in headless Chromium with three.js, fits them into one cell, crops every frame to its opaque bounds
// and writes:
//   client/Assets/Bloomlings/Art/Heroes/Resources/HeroMotion/<family>-<clip>-<NN>.png   the frames
//   client/Assets/Bloomlings/UI/Design/HeroMotionData.cs                               crops and head points (kit)
//   client/Assets/Bloomlings/Art/Heroes/Resources/HeroMotion/manifest.json             the files (originality test)
//   tools/heroanim/manifest.json                                                       hashes for check.mjs
// Usage: node bake.mjs [--only <family>]
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { PNG } from 'pngjs';
import { chromium } from 'playwright-core';
import { serve } from './serve.mjs';
import { palette, indexed, writePng8 } from './png8.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '..', '..');
export const framesDir = path.join(repo, 'client', 'Assets', 'Bloomlings', 'Art', 'Heroes', 'Resources', 'HeroMotion');
export const dataFile = path.join(repo, 'client', 'Assets', 'Bloomlings', 'UI', 'Design', 'HeroMotionData.cs');
export const manifestFile = path.join(here, 'manifest.json');
export const configFile = path.join(here, 'heroes.json');
export const recordFile = 'tools/heroanim/SOURCE.md';

export const sha256 = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
export const frameName = (family, clip, i) => `${family}-${clip}-${String(i).padStart(2, '0')}`;

// The opaque bounds of a straight-alpha RGBA picture, or null when it is empty.
function bounds(png) {
  let x0 = png.width, y0 = png.height, x1 = -1, y1 = -1;
  for (let y = 0; y < png.height; y++) {
    for (let x = 0; x < png.width; x++) {
      if (png.data[(y * png.width + x) * 4 + 3] === 0) continue;
      if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y;
    }
  }
  return x1 < 0 ? null : { x: x0, y: y0, w: x1 - x0 + 1, h: y1 - y0 + 1 };
}

function crop(png, b) {
  const out = new PNG({ width: b.w, height: b.h });
  for (let y = 0; y < b.h; y++) {
    png.data.copy(out.data, y * b.w * 4, ((b.y + y) * png.width + b.x) * 4, ((b.y + y) * png.width + b.x + b.w) * 4);
  }
  return out;
}

const f4 = v => (Math.round(v * 10000) / 10000).toString();

function csharp(config, results) {
  const lines = [];
  lines.push('// <auto-generated>');
  lines.push('// Written by tools/heroanim/bake.mjs from tools/heroanim/heroes.json; do not edit. `node tools/heroanim/check.mjs`');
  lines.push('// proves it still matches the frames.');
  lines.push('// </auto-generated>');
  lines.push('namespace Bloomlings.Client.UI.Design');
  lines.push('{');
  lines.push('    public static partial class HeroMotion');
  lines.push('    {');
  lines.push(`        /// <summary>The frame cell's width in pixels (every frame is cropped from one ${config.cell[0]} × ${config.cell[1]} cell).</summary>`);
  lines.push(`        public const int CellWidth = ${config.cell[0]};`);
  lines.push('');
  lines.push('        /// <summary>The frame cell\'s height in pixels.</summary>');
  lines.push(`        public const int CellHeight = ${config.cell[1]};`);
  lines.push('');
  lines.push('        /// <summary>Where the hero\'s feet stand, as a share of the cell\'s height.</summary>');
  lines.push(`        public const float FootLine = ${f4(config.feet)}f;`);
  lines.push('');
  lines.push('        /// <summary>The frames per second of every clip.</summary>');
  lines.push(`        public const int Fps = ${config.fps};`);
  lines.push('');
  lines.push('        // Per clip: the family, the clip, then per frame its crop in the cell (x, y, width, height in pixels) and its');
  lines.push('        // head points as shares of the cell (the head bone at the chin and the head\'s top at the brow: x, y each).');
  lines.push('        private static readonly ClipData[] ClipTable =');
  lines.push('        {');
  for (const r of results) {
    for (const clip of ['idle', 'react', 'win']) {
      const fr = r.frames.filter(f => f.clip === clip);
      if (fr.length === 0) continue;
      lines.push(`            new ClipData("${r.family}", "${clip}",`);
      lines.push('                new short[]');
      lines.push('                {');
      for (const f of fr) lines.push(`                    ${f.crop.x}, ${f.crop.y}, ${f.crop.w}, ${f.crop.h},`);
      lines.push('                },');
      lines.push('                new float[]');
      lines.push('                {');
      for (const f of fr) lines.push(`                    ${[...f.head, ...f.top].map(v => f4(v) + 'f').join(', ')},`);
      lines.push('                }),');
    }
  }
  lines.push('        };');
  lines.push('    }');
  lines.push('}');
  return lines.join('\n') + '\n';
}

async function main() {
  const config = JSON.parse(fs.readFileSync(configFile, 'utf8'));
  const only = process.argv.includes('--only') ? process.argv[process.argv.indexOf('--only') + 1] : null;
  const old = fs.existsSync(manifestFile) ? JSON.parse(fs.readFileSync(manifestFile, 'utf8')) : null;
  fs.mkdirSync(framesDir, { recursive: true });

  const { server, port } = await serve();
  const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
  const page = await browser.newPage({ viewport: { width: 256, height: 256 } });
  page.on('pageerror', e => console.error('page error:', e.message));
  page.on('console', m => { if (m.type() === 'error' && !/404/.test(m.text())) console.error('page:', m.text()); });
  await page.goto(`http://127.0.0.1:${port}/page.html`);
  await page.waitForFunction(() => window.ready, null, { timeout: 60000 });

  const results = [];
  for (const hero of config.heroes) {
    if (only && hero.family !== only) {
      const kept = old && old.heroes.find(h => h.family === hero.family);
      if (!kept) throw new Error(`--only ${only}: no earlier bake of ${hero.family} to keep`);
      results.push(kept);
      continue;
    }
    const t0 = Date.now();
    const job = {
      file: hero.file, idle: hero.idle, react: hero.react, win: hero.win || null, head: hero.head || null, top: hero.top || null,
      fps: config.fps,
      // A hero's own clip lengths (null: the clips' own spans) before the shared ones (the owner's table).
      idleSeconds: 'idleSeconds' in hero ? hero.idleSeconds : config.idleSeconds,
      reactSeconds: 'reactSeconds' in hero ? hero.reactSeconds : config.reactSeconds,
      idleBlend: config.idleBlend, reactIn: config.reactIn, reactOut: config.reactOut,
      yaw: hero.yaw, pitch: config.pitch, fov: config.fov,
      // A hero's own light settings (heroes.json `light`: hemi, key, fill, rim, exposure, lift) over the shared ones.
      light: { ...config.light, ...(hero.light || {}) },
      // A hero's own color grade of its texture (heroes.json `color`: gamma, gain, saturation, warm), or none.
      color: hero.color || null,
      cell: config.cell, feet: config.feet, fill: config.fill, margin: config.margin,
      width: Math.round(config.cell[0] * config.supersample), height: Math.round(config.cell[1] * config.supersample),
    };
    const baked = await page.evaluate(j => window.bake(j), job);
    for (const f of fs.readdirSync(framesDir)) if (f.startsWith(hero.family + '-') && f.endsWith('.png')) fs.rmSync(path.join(framesDir, f));
    const frames = [];
    const pictures = [];
    const index = { idle: 0, react: 0, win: 0 };
    const [cw, ch] = config.cell;
    const share = p => [p[0] / cw, p[1] / ch];
    for (const f of baked.frames) {
      const png = PNG.sync.read(Buffer.from(f.png.split(',')[1], 'base64'));
      const b = bounds(png);
      if (!b) throw new Error(`${hero.family}: an empty frame`);
      pictures.push(crop(png, b));
      frames.push({ name: frameName(hero.family, f.clip, index[f.clip]++), clip: f.clip, crop: b, head: share(f.head), top: share(f.top) });
    }
    // One palette for all the hero's frames (png8.mjs), so the files stay small and no color flickers.
    const pal = palette(pictures);
    frames.forEach((f, i) => {
      const bytes = writePng8(pictures[i].width, pictures[i].height, indexed(pictures[i], pal), pal);
      fs.writeFileSync(path.join(framesDir, f.name + '.png'), bytes);
      f.sha256 = sha256(bytes);
      f.bytes = bytes.length;
    });
    const total = frames.reduce((s, f) => s + f.bytes, 0);
    console.log(`${hero.family}: ${index.idle} idle + ${index.react} reaction${index.win ? ` + ${index.win} win` : ''} frames, ${(total / 1024 / 1024).toFixed(2)} MB, scale ${baked.scale.toFixed(3)}, ${((Date.now() - t0) / 1000).toFixed(1)} s`);
    results.push({ family: hero.family, model: hero.file, modelSha256: sha256(fs.readFileSync(path.join(here, 'models', hero.file))), frames });
  }
  await browser.close();
  server.close();

  const configSha256 = sha256(fs.readFileSync(configFile));
  const data = csharp(config, results);
  fs.writeFileSync(dataFile, data);
  fs.writeFileSync(manifestFile, JSON.stringify({ config: 'heroes.json', configSha256, data: path.relative(repo, dataFile), dataSha256: sha256(Buffer.from(data)), heroes: results }, null, 1) + '\n');
  // The frames folder's own list, in tools/artgen's manifest shape: the content suite's originality test accepts exactly
  // these files under the folder's licence record (client/THIRD_PARTY_NOTICES.md), as owner pictures with this record.
  const files = results.flatMap(r => r.frames.map(f => ({ path: f.name + '.png', width: f.crop.w, height: f.crop.h, sha256: f.sha256, slot: `char.hero3d.motion.${r.family}`, source: 'owner', record: recordFile })));
  fs.writeFileSync(path.join(framesDir, 'manifest.json'), JSON.stringify({ tool: 'tools/heroanim/bake.mjs', files }, null, 1) + '\n');
  const all = results.flatMap(r => r.frames);
  console.log(`${all.length} frames, ${(all.reduce((s, f) => s + f.bytes, 0) / 1024 / 1024).toFixed(2)} MB`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch(e => { console.error(e); process.exit(1); });
}
