using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Bloomlings.Client.UI.Design;

namespace Bloomlings.Playtest.Preview
{
    /// <summary>
    /// Writes the asset inventory (spec 002 US4, FR-029, FR-030) from the slot registry. The document is generated;
    /// edits go to <c>client/Assets/Bloomlings/UI/Design/AssetSlots.cs</c>.
    /// </summary>
    public static class Inventory
    {
        public static string Markdown(ISet<string> playtest, string root)
        {
            ISet<string> unity = Coverage.UnityReferences(root);
            var md = new StringBuilder();
            md.AppendLine("# Asset Inventory: the art and audio that replace the placeholders");
            md.AppendLine();
            md.AppendLine("**Feature**: [spec 002](spec.md) (User Story 4, FR-029, FR-030, SC-003) | **Reference**: [design board](ux-design-board.webp)");
            md.AppendLine();
            md.AppendLine("<!-- Generated by `dotnet run --project playtest/preview -- --inventory` from");
            md.AppendLine("     client/Assets/Bloomlings/UI/Design/AssetSlots.cs. Do not edit by hand. -->");
            md.AppendLine();
            md.AppendLine("Every visual and sound the game now draws or plays as a placeholder has a slot here. Every slot is drawn or played");
            md.AppendLine("somewhere in the game, or it is marked \"not in the game yet\". The id is the placeholder's name in code, so each final");
            md.AppendLine("asset replaces exactly one placeholder.");
            md.AppendLine();
            md.AppendLine("How to read the columns:");
            md.AppendLine();
            md.AppendLine("- **Frames** are the numbers on the design board.");
            md.AppendLine("- **Size**:");
            md.AppendLine("  - Icon: up to 96 px;");
            md.AppendLine("  - Small: up to 192 px;");
            md.AppendLine("  - Medium: up to 512 px;");
            md.AppendLine("  - Large: up to 1024 px;");
            md.AppendLine("  - Screen: full screen, portrait, from 16:9 to 21:9.");
            md.AppendLine("- **Readable**: the asset must stay readable at small sizes and pass the readability checks of spec 001:");
            md.AppendLine("  grayscale and icon, small size, color distance, and the pod, slot and moving-character tests.");
            md.AppendLine("- **Priority**: Launch means needed for launch; Later means it can follow.");
            md.AppendLine();

            md.AppendLine("## Summary");
            md.AppendLine();
            md.AppendLine("| Category | Launch | Later | Total |");
            md.AppendLine("|---|---|---|---|");
            foreach (IGrouping<AssetCategory, AssetSlot> group in AssetSlots.All.GroupBy(s => s.Category).OrderBy(g => g.Key))
            {
                md.AppendLine($"| {Name(group.Key)} | {group.Count(s => s.Priority == AssetPriority.Launch)} | {group.Count(s => s.Priority == AssetPriority.Later)} | {group.Count()} |");
            }

            md.AppendLine($"| **All** | **{AssetSlots.All.Count(s => s.Priority == AssetPriority.Launch)}** | **{AssetSlots.All.Count(s => s.Priority == AssetPriority.Later)}** | **{AssetSlots.All.Count}** |");
            md.AppendLine();

            foreach (IGrouping<AssetCategory, AssetSlot> group in AssetSlots.All.GroupBy(s => s.Category).OrderBy(g => g.Key))
            {
                md.AppendLine("## " + Name(group.Key));
                md.AppendLine();
                if (group.Key == AssetCategory.UiKit)
                {
                    // Spec 003 FR-030: the final UI art follows the Garden look.
                    md.AppendLine("Final art for every entry here follows the Garden look of spec 003: a flat cream plate with a thin brown");
                    md.AppendLine("outline, a slightly raised face in its color set with a darker lip and a soft highlight, volumetric");
                    md.AppendLine("sentence-case labels in Nunito, and, on the main buttons only, the leaves and white flowers of");
                    md.AppendLine("`ui.deco.garden`. Cards and the sheet are paper in a wooden frame with a header band.");
                    md.AppendLine();
                }
                else if (group.Key == AssetCategory.Typography)
                {
                    md.AppendLine("The fonts are bundled files, the only new files of spec 003: Nunito ExtraBold and SemiBold (SIL OFL 1.1, with");
                    md.AppendLine("`OFL.txt`) in `client/Assets/Bloomlings/UI/Fonts/Resources/`, covering Latin and Cyrillic.");
                    md.AppendLine();
                }

                md.AppendLine("| Id | What | Frames | Where | States or variants | Size | Readable | Priority | Placeholder now |");
                md.AppendLine("|---|---|---|---|---|---|---|---|---|");
                foreach (AssetSlot slot in group)
                {
                    string frames = slot.Frames.Count == 0 ? "—" : string.Join(", ", slot.Frames);
                    string where = string.Join("; ", slot.UsedIn);
                    string placeholder = slot.Placeholder + (Coverage.NotDrawnYet(slot) ? " (not in the game yet)" : string.Empty);
                    md.AppendLine($"| `{slot.Id}` | {slot.Title} | {frames} | {where} | {string.Join("; ", slot.States)} | {slot.Size} | {(slot.Readability ? "yes" : "no")} | {slot.Priority} | {placeholder} |");
                }

                md.AppendLine();
            }

            return md.ToString().Replace("\r\n", "\n");
        }

        private static string Name(AssetCategory category) => category switch
        {
            AssetCategory.Brand => "Brand",
            AssetCategory.Background => "Backgrounds",
            AssetCategory.Character => "Bloomling characters",
            AssetCategory.VariantSymbol => "Variant symbols",
            AssetCategory.BoardTile => "Board tiles and overlays",
            AssetCategory.Special => "Specials",
            AssetCategory.PodSlot => "Pods and slots",
            AssetCategory.Booster => "Booster icons",
            AssetCategory.UiKit => "UI kit",
            AssetCategory.Currency => "Currency and rewards",
            AssetCategory.CollectionFrame => "Collection frames",
            AssetCategory.Cosmetic => "Cosmetics",
            AssetCategory.Effect => "Visual effects",
            AssetCategory.Typography => "Typography",
            _ => "Audio",
        };
    }
}
